// packages/ez-react/src/components/addons/tooltip/Tooltip.tsx
import React, { DOMAttributes, FC, useMemo } from 'react';
import {
  defaultTooltipOffset,
  initialTooltipStyle,
  tooltipAnimationOptions,
} from 'eazychart-core/src';
import {
  AnimationOptions,
  NormalizedDatum,
  Point,
  ShapeDatum,
} from 'eazychart-core/src/types';
import { useAnimation } from '@/lib/use-animation';

export interface TooltipProps extends DOMAttributes<HTMLDivElement> {
  offset?: Point;
  datum: NormalizedDatum | null;
  shapeDatum: ShapeDatum | null;
  isVisible: boolean;
  mousePosition: Point;
  animationOptions?: AnimationOptions;
}

export const Tooltip: FC<TooltipProps> = ({
  offset = defaultTooltipOffset,
  datum,
  shapeDatum,
  isVisible,
  mousePosition,
  animationOptions = tooltipAnimationOptions,
  ...rest
}) => {
  const targetStyle = useMemo(
    () => ({
      left: `${mousePosition.x ? mousePosition.x + offset.x : 0}px`,
      top: `${mousePosition.y ? mousePosition.y + offset.y : 0}px`,
      opacity: isVisible ? 1.0 : 0.0,
    }),
    [mousePosition, isVisible, offset]
  );

  const animatedStyle = useAnimation<any>(
    targetStyle,
    initialTooltipStyle,
    animationOptions,
    [offset]
  );

  const { id, color, label, ...attributes } = datum || {
    color: undefined,
  };

  return datum ? (
    <div className="ez-tooltip" style={animatedStyle} {...rest}>
      {shapeDatum?.color && (
        <div
          className="ez-tooltip-color"
          style={{ backgroundColor: shapeDatum.color }}
        ></div>
      )}
      <div className="ez-tooltip-text">
        {Object.keys(attributes).map((attribute) => (
          <div key={attribute} className={`ez-tooltip-attribute ${attribute}`}>
            <div className="ez-tooltip-attribute--name">{attribute} :</div>
            <div className="ez-tooltip-attribute--value">
              {datum[attribute] as string}
            </div>
          </div>
        ))}
      </div>
    </div>
  ) : null;
};

// packages/ez-vue/src/components/addons/tooltip/Tooltip.tsx
import { PropType } from 'vue';
import Component, { mixins } from 'vue-class-component';
import {
  AnimationOptions,
  NormalizedDatum,
  Point,
  ShapeDatum,
} from 'eazychart-core/src/types';
import { Prop } from 'vue-property-decorator';
import {
  defaultTooltipOffset,
  initialTooltipStyle,
  tooltipAnimationOptions,
} from 'eazychart-core/src';
import AnimationMixin from '@/lib/AnimationMixin';

type TooltipAnimationStyle = {
  left: string;
  top: string;
  opacity: number;
};

export interface TooltipProps {
  offset?: Point;
  datum: NormalizedDatum | null;
  shapeDatum: ShapeDatum | null;
  isVisible: boolean;
  mousePosition: Point;
}

@Component
export default class Tooltip extends mixins(AnimationMixin) {
  @Prop({
    type: Object as PropType<Point>,
    default() {
      return defaultTooltipOffset;
    },
  })
  private readonly offset!: Point;

  @Prop({
    type: Object as PropType<NormalizedDatum>,
    default() {
      return null;
    },
  })
  private readonly datum!: NormalizedDatum | null;

  @Prop({
    type: Object as PropType<ShapeDatum>,
    default() {
      return null;
    },
  })
  private readonly shapeDatum!: ShapeDatum | null;

  @Prop({
    type: Boolean,
    default() {
      return false;
    },
  })
  private readonly isVisible!: boolean;

  @Prop({
    type: Object as PropType<Point>,
    default() {
      return { x: 0, y: 0 };
    },
  })
  private readonly mousePosition!: Point;

  @Prop({
    type: Object as PropType<AnimationOptions>,
    default() {
      return tooltipAnimationOptions;
    },
  })
  private readonly animationOptions!: AnimationOptions;

  private animatedStyle: TooltipAnimationStyle = initialTooltipStyle;

  get targetStyle() {
    return {
      left: `${
        this.mousePosition.x ? this.mousePosition.x + this.offset.x : 0
      }px`,
      top: `${
        this.mousePosition.y ? this.mousePosition.y + this.offset.y : 0
      }px`,
      opacity: this.isVisible ? 1.0 : 0.0,
    };
  }

  get animationArguments() {
    return {
      from: this.animatedStyle,
      to: this.targetStyle,
      options: this.animationOptions,
      onUpdate: (v: TooltipAnimationStyle) => (this.animatedStyle = v),
      dependencies: ['targetStyle'],
    };
  }

  render() {
    const { animatedStyle, datum, shapeDatum } = this;

    const { id: _id, label: _label, ...attributes } = datum || {};

    return datum ? (
      <div class="ez-tooltip" style={animatedStyle}>
        {shapeDatum?.color && (
          <div
            class="ez-tooltip-color"
            style={{ backgroundColor: shapeDatum.color }}
          ></div>
        )}
        <div class="ez-tooltip-text">
          {Object.keys(attributes).map((attribute) => (
            <div key={attribute} class={`ez-tooltip-attribute ${attribute}`}>
              <div class="ez-tooltip-attribute--name">{attribute} :</div>
              <div class="ez-tooltip-attribute--value">
                {datum[attribute] as string}
              </div>
            </div>
          ))}
        </div>
      </div>
    ) : (
      <div class="ez-tooltip" style={animatedStyle}></div>
    );
  }
}
