// packages/ez-vue/src/components/IrregularArcs.tsx
import Vue, { PropType } from 'vue';
import Component from 'vue-class-component';
import { ChartContext, Dimensions, Point } from 'eazychart-core/src/types';
import { InjectReactive, Prop, Watch } from 'vue-property-decorator';
import { ScaleLinear, scalePieArcData } from 'eazychart-core/src';
import Arc from '@/components/shapes/Arc';

@Component({ components: { Arc } })
export default class IrregularArcs extends Vue {
  @InjectReactive('chart')
  private chart!: ChartContext;

  @Prop({
    type: Object as PropType<ScaleLinear>,
    required: true,
  })
  private readonly aScale!: ScaleLinear;

  @Prop({
    type: Object as PropType<ScaleLinear>,
    required: true,
  })
  private readonly rScale!: ScaleLinear;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly donutRadius!: number;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly cornerRadius!: number;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly padAngle!: number;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly padRadius!: number;

  @Prop({
    type: String,
  })
  private readonly stroke!: string;

  @Prop({
    type: Number,
  })
  private readonly strokeWidth!: number;

  @Prop({
    type: Function,
    default: ({ width, height }: Dimensions) => ({
      x: width / 2,
      y: height / 2,
    }),
  })
  private readonly getCenter!: (dimensions: Dimensions) => Point;

  @Prop({
    type: Function,
    default: ({ width, height }: Dimensions) => Math.min(width, height) / 2,
  })
  private readonly getRadius!: (dimensions: Dimensions) => number;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly startAngle!: number;

  @Prop({
    type: Number,
    default: 2 * Math.PI,
  })
  private readonly endAngle!: number;

  @Prop({
    type: Function,
  })
  private readonly sortValues!: undefined | ((a: number, b: number) => number);

  get radius() {
    return this.getRadius(this.chart.dimensions);
  }

  get center() {
    return this.getCenter(this.chart.dimensions);
  }

  get shapeData() {
    return scalePieArcData(
      this.chart.activeData,
      this.aScale,
      this.startAngle,
      this.endAngle,
      this.sortValues,
    );
  }

  created() {
    this.rScale.appendDefinition({
      range: [this.getRadius(this.chart.dimensions) / 2, this.getRadius(this.chart.dimensions)],
    });
  }

  @Watch('radius')
  onRadiusChange() {
    this.rScale.appendDefinition({ range: [this.radius / 2, this.radius] });
  }

  render() {
    const {
      shapeData,
      center,
      cornerRadius,
      padAngle,
      padRadius,
      stroke,
      strokeWidth,
    } = this;

    const minArcValue = this.rScale.scale(
      Math.min(...shapeData.map((shapeDatum) => shapeDatum.value)),
    );

    return (
      <g
        transform={`translate(${center.x},${center.y})`}
        class="ez-irregular-arcs"
      >
        {shapeData.map((shapeDatum) => {
          const outerRadius = this.rScale.scale(shapeDatum.value);
          const innerRadius = minArcValue * this.donutRadius;
          return (
            <Arc
              key={shapeDatum.id}
              shapeDatum={shapeDatum}
              outerRadius={outerRadius}
              innerRadius={innerRadius}
              cornerRadius={cornerRadius}
              padAngle={padAngle}
              padRadius={padRadius}
              stroke={stroke}
              strokeWidth={strokeWidth}
            />
          );
        })}
      </g>
    );
  }
}

// packages/ez-react/src/components/IrregularArcs.tsx
import React, { FC, SVGAttributes, useMemo } from 'react';
import { useChart } from '@/lib/use-chart';
import { Arc } from './shapes/Arc';
import { Dimensions, Point, PieConfig } from 'eazychart-core/src/types';
import { ScaleLinear, scalePieArcData } from 'eazychart-core/src';

export interface IrregularArcsProps
  extends PieConfig,
    Omit<SVGAttributes<SVGPathElement>, 'stroke' | 'strokeWidth'> {
  aScale: ScaleLinear;
  rScale: ScaleLinear;
  getCenter?: (dimensions: Dimensions) => Point;
  getRadius?: (dimensions: Dimensions) => number;
  startAngle?: number;
  endAngle?: number;
}

export const IrregularArcs: FC<IrregularArcsProps> = ({
  startAngle = 0,
  endAngle = 2 * Math.PI,
  aScale,
  rScale,
  getCenter = ({ width, height }) => ({ x: width / 2, y: height / 2 }),
  getRadius = ({ width, height }) => Math.min(width, height) / 2,
  donutRadius = 0,
  cornerRadius = 0,
  padAngle = 0,
  padRadius = 0,
  stroke,
  strokeWidth,
  sortValues,
  ...rest
}) => {
  const { activeData, dimensions } = useChart();
  const center = useMemo(() => getCenter(dimensions), [dimensions, getCenter]);
  const radius = useMemo(() => getRadius(dimensions), [dimensions, getRadius]);
  const radiusScale = useMemo(() => {
    rScale.appendDefinition({ range: [radius / 2, radius] });
    return rScale;
  }, [rScale, radius]);

  const shapeData = useMemo(() => {
    return scalePieArcData(
      activeData,
      aScale,
      startAngle,
      endAngle,
      sortValues
    );
  }, [activeData, aScale, sortValues, startAngle, endAngle]);

  const minArcValue = useMemo(
    () =>
      rScale.scale(
        Math.min(...shapeData.map((shapeDatum) => shapeDatum.value))
      ),
    [rScale, shapeData]
  );

  return (
    <g
      transform={`translate(${center.x},${center.y})`}
      {...rest}
      className="ez-irregular-arcs"
    >
      {shapeData.map((shapeDatum) => {
        const outerRadius = radiusScale.scale(shapeDatum.value);
        const innerRadius = minArcValue * donutRadius;
        return (
          <Arc
            key={shapeDatum.id}
            shapeDatum={shapeDatum}
            outerRadius={outerRadius}
            innerRadius={innerRadius}
            cornerRadius={cornerRadius}
            padAngle={padAngle}
            padRadius={padRadius}
            stroke={stroke}
            strokeWidth={strokeWidth}
          />
        );
      })}
    </g>
  );
};
