// packages/ez-vue/src/components/Pie.tsx
import Vue from 'vue';
import Component from 'vue-class-component';
import { ChartContext, Dimensions, Point } from 'eazychart-core/src/types';
import { InjectReactive, Prop } from 'vue-property-decorator';
import { ScaleOrdinal, scalePieArcData } from 'eazychart-core/src';
import Arc from '@/components/shapes/Arc';

@Component({ components: { Arc } })
export default class Pie extends Vue {
  @InjectReactive('chart')
  private chart!: ChartContext;

  @InjectReactive('colorScale')
  private colorScale!: ScaleOrdinal;

  @Prop({
    type: String,
    default: 0,
  })
  private readonly valueDomainKey!: string;

  @Prop({
    type: String,
    default: 0,
  })
  private readonly labelDomainKey!: string;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly donutRadius!: number;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly cornerRadius!: number;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly padAngle!: number;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly padRadius!: number;

  @Prop({
    type: String,
  })
  private readonly stroke!: string;

  @Prop({
    type: Number,
  })
  private readonly strokeWidth!: number;

  @Prop({
    type: Function,
    default: ({ width, height }: Dimensions) => ({
      x: width / 2,
      y: height / 2,
    }),
  })
  private readonly getCenter!: (dimensions: Dimensions) => Point;

  @Prop({
    type: Function,
    default: ({ width, height }: Dimensions) => Math.min(width, height) / 2,
  })
  private readonly getRadius!: (dimensions: Dimensions) => number;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly startAngle!: number;

  @Prop({
    type: Number,
    default: 2 * Math.PI,
  })
  private readonly endAngle!: number;

  @Prop({
    type: Function,
  })
  private readonly sortValues!: undefined | ((a: number, b: number) => number);

  get radius() {
    const radius = this.getRadius(this.chart.dimensions);
    return {
      outerRadius: radius,
      innerRadius: radius * this.donutRadius,
    };
  }

  get center() {
    return this.getCenter(this.chart.dimensions);
  }

  get shapeData() {
    return scalePieArcData(
      this.chart.data,
      this.valueDomainKey,
      this.labelDomainKey,
      this.colorScale,
      this.startAngle,
      this.endAngle,
      this.sortValues,
    );
  }

  render() {
    const {
      shapeData,
      radius,
      center,
      cornerRadius,
      padAngle,
      padRadius,
      stroke,
      strokeWidth,
    } = this;
    const { outerRadius, innerRadius } = radius;

    return (
      <g transform={`translate(${center.x},${center.y})`} class="ez-pie" data-testid="ez-pie">
        {shapeData.map((shapeDatum) => (
          <Arc
            key={shapeDatum.id}
            shapeDatum={shapeDatum}
            outerRadius={outerRadius}
            innerRadius={innerRadius}
            cornerRadius={cornerRadius}
            padAngle={padAngle}
            padRadius={padRadius}
            stroke={stroke}
            strokeWidth={strokeWidth}
          />
        ))}
      </g>
    );
  }
}

// packages/ez-react/src/components/Pie.tsx
import React, { FC, SVGAttributes, useMemo } from 'react';
import { scalePieArcData } from 'eazychart-core/src';
import { Dimensions, Point, PieConfig } from 'eazychart-core/src/types';
import { useChart } from '@/lib/use-chart';
import { Arc } from '@/components/shapes/Arc';
import { useColorScale } from './scales/ColorScale';

export interface PieProps
  extends PieConfig,
    Omit<SVGAttributes<SVGPathElement>, 'stroke' | 'strokeWidth'> {
  valueDomainKey: string;
  labelDomainKey: string;
  getCenter?: (dimensions: Dimensions) => Point;
  getRadius?: (dimensions: Dimensions) => number;
  startAngle?: number;
  endAngle?: number;
}

export const Pie: FC<PieProps> = ({
  valueDomainKey,
  labelDomainKey,
  startAngle = 0,
  endAngle = 2 * Math.PI,
  getCenter = ({ width, height }) => ({ x: width / 2, y: height / 2 }),
  getRadius = ({ width, height }) => Math.min(width, height) / 2,
  donutRadius = 0,
  cornerRadius = 0,
  padAngle = 0,
  padRadius = 0,
  stroke,
  strokeWidth,
  sortValues,
  ...rest
}) => {
  const { data, dimensions } = useChart();
  const { colorScale } = useColorScale();
  const { width, height } = dimensions;
  const center = getCenter({ width, height });
  const radius = getRadius({ width, height });
  const outerRadius = radius;
  const innerRadius = radius * donutRadius;

  const shapeData = useMemo(() => {
    return scalePieArcData(
      data,
      valueDomainKey,
      labelDomainKey,
      colorScale,
      startAngle,
      endAngle,
      sortValues
    );
  }, [
    data,
    valueDomainKey,
    labelDomainKey,
    colorScale,
    sortValues,
    startAngle,
    endAngle,
  ]);

  return (
    <g
      transform={`translate(${center.x},${center.y})`}
      {...rest}
      className="ez-pie"
      data-testid="ez-pie"
    >
      {shapeData.map((shapeDatum) => {
        return (
          <Arc
            key={shapeDatum.id}
            shapeDatum={shapeDatum}
            outerRadius={outerRadius}
            innerRadius={innerRadius}
            cornerRadius={cornerRadius}
            padAngle={padAngle}
            padRadius={padRadius}
            stroke={stroke}
            strokeWidth={strokeWidth}
          />
        );
      })}
    </g>
  );
};
