// packages/ez-vue/src/components/Segments.tsx
import Vue, { PropType } from 'vue';
import Component from 'vue-class-component';
import { LineConfig, MarkerConfig, PointDatum } from 'eazychart-core/src/types';
import { InjectReactive, Prop } from 'vue-property-decorator';
import { ScaleOrdinal } from 'eazychart-core/src';
import Point from '@/components/shapes/Point';
import LinePath from '@/components/shapes/LinePath';
import Points from '@/components/Points';

@Component({ components: { Point, LinePath } })
export default class Segments extends Vue {
  @InjectReactive('colorScale')
  private colorScale!: ScaleOrdinal;

  @Prop({
    type: String,
    required: true,
  })
  private readonly xDomainKey!: string;

  @Prop({
    type: String,
    required: true,
  })
  private readonly yDomainKey!: string;

  @Prop({
    type: Object as PropType<LineConfig>,
    default() {
      return {
        stroke: '#339999',
        strokeWidth: 2,
        curve: 'curveLinear',
      };
    },
  })
  private readonly line!: LineConfig;

  @Prop({
    type: Object as PropType<MarkerConfig>,
    default() {
      return {
        hidden: true,
        radius: 5,
        color: '#FFF',
      };
    },
  })
  private readonly marker!: MarkerConfig;

  get color() {
    const { colorScale, yDomainKey, line } = this;
    if (colorScale && colorScale.isDefined()) {
      // Segments shape does not support non ordinal color scale
      return (colorScale as any as ScaleOrdinal).scale(yDomainKey);
    }
    return line.stroke;
  }

  render() {
    const {
      xDomainKey, yDomainKey, color, line, marker,
    } = this;

    return (
      <Points
        xDomainKey={xDomainKey}
        yDomainKey={yDomainKey}
        stroke={color}
        scopedSlots={{
          default: ({ shapeData }: { shapeData: PointDatum[] }) => {
            const pointData: PointDatum[] = shapeData.map((pointDatum) => ({
              ...pointDatum,
              color,
            }));
            return (
              <g class="ez-segments">
                <LinePath
                  shapeData={pointData}
                  curve={line.curve}
                  beta={line.beta}
                  stroke={color}
                  strokeWidth={line.strokeWidth}
                />
                {!marker.hidden
                  && pointData.map((pointDatum) => (
                      <Point
                        key={pointDatum.id}
                        shapeDatum={pointDatum}
                        r={marker.radius}
                        fill={marker.color}
                        stroke={color}
                        strokeWidth={line.strokeWidth}
                      />
                  ))}
              </g>
            );
          },
        }}
      />
    );
  }
}

// packages/ez-react/src/components/Segments.tsx
import React, { FC, SVGAttributes, useMemo } from 'react';
import { LineConfig, MarkerConfig, PointDatum } from 'eazychart-core/src/types';
import { Point } from '@/components/shapes/Point';
import { Points } from '@/components/Points';
import { LinePath } from '@/components/shapes/LinePath';
import { useColorScale } from '@/components/scales/ColorScale';
import { ScaleOrdinal } from 'eazychart-core/src';

export interface SegmentsProps extends SVGAttributes<SVGGElement> {
  xDomainKey: string;
  yDomainKey: string;
  line?: LineConfig;
  marker?: MarkerConfig;
}

export const Segments: FC<SegmentsProps> = ({
  xDomainKey,
  yDomainKey,
  line = {
    stroke: '#339999',
    strokeWidth: 2,
    curve: 'curveLinear',
    beta: 0,
  },
  marker = {
    hidden: true,
    radius: 5,
    color: '#FFF',
  },
}) => {
  const { colorScale } = useColorScale();

  const color = useMemo(() => {
    if (colorScale.isDefined()) {
      // Segment shape does not support non ordinal color scale
      return (colorScale as any as ScaleOrdinal).scale(yDomainKey);
    }
    return line.stroke;
  }, [colorScale, yDomainKey, line]);

  return (
    <Points
      xDomainKey={xDomainKey}
      yDomainKey={yDomainKey}
      stroke={color}
      scopedSlots={{
        default: ({ shapeData }) => {
          const pointData: PointDatum[] = shapeData.map((pointDatum) => ({
            ...pointDatum,
            color,
          }));
          return (
            <g className="ez-segments">
              <LinePath
                shapeData={pointData}
                curve={line.curve}
                beta={line.beta}
                stroke={color}
                strokeWidth={line.strokeWidth}
              />
              {!marker.hidden &&
                pointData.map((pointDatum) => {
                  return (
                    <Point
                      key={pointDatum.id}
                      shapeDatum={pointDatum}
                      r={marker.radius}
                      fill={marker.color}
                      stroke={color}
                      strokeWidth={line.strokeWidth}
                    />
                  );
                })}
            </g>
          );
        },
      }}
    />
  );
};
