// packages/ez-vue/src/components/scales/Axis.tsx
import Vue, { PropType } from 'vue';
import Component from 'vue-class-component';
import { InjectReactive, Prop, Watch } from 'vue-property-decorator';
import {
  defaultAxis,
  getAxis,
  getAxisLabelAttributes,
  getAxisPath,
  getAxisTickByCoordinate,
  getAxisTitleProps,
  getTickTextAnchorByPosition,
  transformTranslate,
  animate,
  ScaleBand,
  ScaleLinear,
} from 'eazychart-core/src';
import {
  Anchor, ChartContext, Position, AxisData,
} from 'eazychart-core/src/types';

@Component
export default class Axis extends Vue {
  @InjectReactive('chart')
  private chart!: ChartContext;

  @Prop({
    type: String as PropType<Position>,
    default() {
      return Position.LEFT;
    },
  })
  private readonly position!: Position;

  @Prop({
    type: Object as PropType<ScaleBand | ScaleLinear>,
    required: true,
  })
  private readonly aScale!: ScaleBand | ScaleLinear;

  @Prop({
    type: Number,
    default: 1,
  })
  private readonly tickLength!: number;

  @Prop({
    type: Number,
    default: 10,
  })
  private readonly tickCount!: number;

  @Prop({
    type: Number,
    default: 6,
  })
  private readonly tickSize!: number;

  @Prop({
    type: Function,
    default: null,
  })
  private readonly tickFormat!: Function;

  @Prop({
    type: String,
    default: null,
  })
  private readonly title!: string;

  @Prop({
    type: String,
    default: Anchor.MIDDLE,
  })
  private readonly titleAlign!: Anchor;

  private currentAxis: AxisData = defaultAxis;

  private cancelAnimation: Function | null = null;

  private axisLabelTransform = {
    textAnchor: Anchor.MIDDLE,
    transform: 'translate(0, 0) rotate(0 0 0)',
  };

  updateCurrentAxis() {
    this.cancelAnimation && this.cancelAnimation();
    const axis = getAxis(
      this.position,
      this.aScale.scale,
      this.chart.dimensions,
      {
        tickCount: this.tickCount,
        tickSize: this.tickSize,
        tickFormat: this.tickFormat,
      },
    );
    this.cancelAnimation = animate(
      this.currentAxis,
      axis,
      this.chart.animationOptions,
      (v: AxisData) => (this.currentAxis = v),
    );
  }

  getTick(tick = 0) {
    return getAxisTickByCoordinate(tick, this.tickLength);
  }

  updateAxisLabelTransform() {
    this.$nextTick(() => {
      const axisElement = this.$refs.axis as SVGGraphicsElement;
      const labels = Array.from(
        axisElement?.querySelectorAll('.ez-axis-tick-text'),
      ) as SVGGraphicsElement[];
      this.axisLabelTransform = getAxisLabelAttributes(
        this.aScale.scale,
        labels,
        this.position,
        'auto',
        this.aScale.definition.reverse,
      );
    });
  }

  created() {
    this.updateCurrentAxis();
    this.updateAxisLabelTransform();
  }

  @Watch('aScale', { deep: true })
  onScalesChange() {
    this.updateCurrentAxis();
  }

  @Watch('position')
  onPositionChange() {
    this.updateCurrentAxis();
  }

  @Watch('currentAxis')
  onAxisChange() {
    this.updateAxisLabelTransform();
  }

  get textAnchor() {
    return getTickTextAnchorByPosition(this.position);
  }

  get currentAxisTransform() {
    return transformTranslate({
      x: this.currentAxis.x,
      y: this.currentAxis.y,
    });
  }

  get axisPath() {
    return getAxisPath(this.currentAxis.path, this.position);
  }

  get titleProps() {
    return getAxisTitleProps(
      this.position,
      this.chart.dimensions,
      this.chart.padding,
      this.titleAlign,
    );
  }

  render() {
    const {
      title,
      titleProps,
      textAnchor,
      currentAxisTransform,
      axisLabelTransform,
      axisPath,
      currentAxis,
      getTick,
    } = this;
    return (
      <g
        class="ez-axis"
        text-anchor={textAnchor}
        transform={currentAxisTransform}
        ref="axis"
      >
        <path class="ez-axis-path" d={axisPath}></path>
        {currentAxis.ticks.map((tick, index) => (
          <g
            key={index}
            class="ez-axis-tick"
            transform={transformTranslate(tick.transform)}
          >
            <line
              class="ez-axis-tick-line"
              x2={getTick(tick.line.x2)}
              y2={getTick(tick.line.y2)}
            />
            <text
              x={tick.text.x}
              y={tick.text.y}
              dy={`${tick.text.dy}em`}
              text-anchor={axisLabelTransform.textAnchor}
              transform={axisLabelTransform.transform}
              class="ez-axis-tick-text"
            >
              {tick.text.text.replace(/(\.\d{1}).*$/, (_a, c) => c)}
            </text>
          </g>
        ))}
        {title && (
          <text
            text-anchor={titleProps.textAnchor}
            transform={titleProps.transform}
            dy={titleProps.dy}
            alignment-baseline={'middle'}
            class="ez-axis-title"
          >
            {title}
          </text>
        )}
      </g>
    );
  }
}

// packages/ez-react/src/components/scales/Axis.tsx
import React, { FC, SVGAttributes, useCallback, useMemo, useRef } from 'react';
import {
  AxisTickConfig,
  AxisTitleConfig,
  Anchor,
  Position,
  AxisTick,
  AxisData,
} from 'eazychart-core/src/types';
import {
  getAxis,
  getAxisTickByCoordinate,
  getAxisPath,
  transformTranslate,
  getTickTextAnchorByPosition,
  defaultAxis,
  getAxisTitleProps,
  getAxisLabelAttributes,
  ScaleLinear,
  ScaleBand,
} from 'eazychart-core/src';
import { useAnimation } from '@/lib/use-animation';
import { useChart } from '@/lib/use-chart';

export interface AxisProps
  extends SVGAttributes<SVGRectElement>,
    AxisTickConfig,
    AxisTitleConfig {
  position?: Position;
  aScale: ScaleBand | ScaleLinear;
  tickLength?: number;
}

export const Axis: FC<AxisProps> = ({
  position = Position.LEFT,
  aScale,
  tickLength = 1,
  tickCount = 10,
  tickSize = 6,
  tickFormat,
  title,
  titleAlign = Anchor.MIDDLE,
}) => {
  const labelsRef = useRef<Array<SVGTextElement | null>>([]);
  const { dimensions, animationOptions, padding } = useChart();
  const targetAxis = useMemo(() => {
    return getAxis(position, aScale.scale, dimensions, {
      tickCount,
      tickSize,
      tickFormat,
    });
  }, [position, dimensions, aScale.scale, tickCount, tickSize, tickFormat]);

  const currentAxis = useAnimation<AxisData>(
    targetAxis,
    defaultAxis,
    animationOptions
  );

  const getTick = useCallback(
    (tick: number) => getAxisTickByCoordinate(tick, tickLength),
    [tickLength]
  );

  const axisPath = useMemo(
    () => getAxisPath(currentAxis.path, position),
    [currentAxis, position]
  );

  const textAnchor = getTickTextAnchorByPosition(position);

  const currentAxisTransform = useMemo(
    () =>
      transformTranslate({
        x: currentAxis.x,
        y: currentAxis.y,
      }),
    [currentAxis]
  );

  const axisLabelTransform = useMemo(() => {
    const labels = labelsRef.current.filter((el) => !!el) as SVGTextElement[];
    return getAxisLabelAttributes(
      aScale.scale,
      labels,
      position,
      'auto',
      aScale.definition.reverse
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentAxis]);

  const titleProps = useMemo(() => {
    return getAxisTitleProps(position, dimensions, padding, titleAlign);
  }, [position, dimensions, padding, titleAlign]);

  return (
    <g
      textAnchor={textAnchor}
      transform={currentAxisTransform}
      className="ez-axis"
    >
      <path d={axisPath} className="ez-axis-path"></path>
      {currentAxis.ticks
        .filter((tick: AxisTick) => tick.text.text !== undefined)
        .map((tick: AxisTick, index: number) => {
          return (
            <g
              key={index}
              transform={transformTranslate(tick.transform)}
              className="ez-axis-tick"
            >
              <line
                x2={getTick(tick.line.x2 || 0)}
                y2={getTick(tick.line.y2 || 0)}
                className="ez-axis-tick-line"
              />
              <text
                x={tick.text.x}
                y={tick.text.y}
                dy={`${tick.text.dy}em`}
                textAnchor={axisLabelTransform.textAnchor}
                transform={axisLabelTransform.transform}
                className="ez-axis-tick-text"
                ref={(el) => (labelsRef.current[index] = el)}
              >
                {tick.text.text.replace(/(\.\d{1}).*$/, (_a, c) => c)}
              </text>
            </g>
          );
        })}
      {title && (
        <text
          {...titleProps}
          alignmentBaseline={'middle'}
          className="ez-axis-title"
        >
          {title}
        </text>
      )}
    </g>
  );
};
