// packages/ez-vue/src/components/scales/LinearScale.tsx
import Vue, { PropType } from 'vue';
import Component from 'vue-class-component';
import {
  InjectReactive,
  Prop,
  ProvideReactive,
  Watch,
} from 'vue-property-decorator';
import { ChartContext, ScaleLinearDefinition } from 'eazychart-core/src/types';
import { ScaleLinear } from 'eazychart-core/src';
import Fragment from '@/lib/Fragment';

@Component
export default class LinearScale extends Vue {
  @InjectReactive('chart')
  private chart!: ChartContext;

  @ProvideReactive('linearScale')
  private linearScale = new ScaleLinear();

  @Prop({
    type: Object as PropType<ScaleLinearDefinition>,
    required: true,
  })
  private readonly definition!: ScaleLinearDefinition;

  mounted() {
    this.defineScale();
  }

  @Watch('chart.dimensions')
  @Watch('chart.data')
  recomputeScale() {
    const { dimensions, data } = this.chart;
    this.linearScale.computeScale(dimensions, data);
  }

  @Watch('chart.definition')
  defineScale() {
    const { definition } = this;
    const { dimensions, data } = this.chart;
    this.linearScale = new ScaleLinear(definition);
    this.linearScale.computeScale(dimensions, data);
  }

  render() {
    const DefaultSlot = this.$scopedSlots.default
      ? this.$scopedSlots.default({})
      : null;
    return (
      <Fragment type="g" name="linear-scale">
        {DefaultSlot}
      </Fragment>
    );
  }
}

// packages/ez-react/src/components/scales/LinearScale.tsx
import React, {
  createContext,
  FC,
  useContext,
  useEffect,
  useMemo,
} from 'react';
import { useChart } from '@/lib/use-chart';
import { ScaleLinear } from 'eazychart-core/src';
import { ScaleLinearDefinition } from 'eazychart-core/src/types';
import { Fragment } from '@/lib/Fragment';

const LinearScaleContext = createContext<{
  linearScale: ScaleLinear;
}>({
  linearScale: new ScaleLinear(),
});

export const useLinearScale = () => {
  return useContext(LinearScaleContext);
};

export const LinearScale: FC<ScaleLinearDefinition> = ({
  children,
  ...definition
}) => {
  const { data, dimensions } = useChart();

  const linearScale = useMemo<ScaleLinear>(() => {
    const scale = new ScaleLinear(definition);
    scale.computeScale(dimensions, data);
    return scale;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [definition]);

  useEffect(() => {
    linearScale.computeScale(dimensions, data);
  }, [dimensions, data, linearScale]);

  return (
    <LinearScaleContext.Provider value={{ linearScale }}>
      <Fragment type="g" name="linear-scale">
        {children}
      </Fragment>
    </LinearScaleContext.Provider>
  );
};
