// packages/ez-react/src/recipes/line/LineErrorMarginChart.tsx
import React, { FC, SVGAttributes, useMemo } from 'react';
import { TooltipProps, Tooltip } from '@/components/addons/tooltip/Tooltip';
import { Chart } from '@/components/Chart';
import { Points } from '@/components/Points';
import { Axis } from '@/components/scales/Axis';
import { Grid } from '@/components/scales/grid/Grid';
import { LinePath } from '@/components/shapes/LinePath';
import { Point } from '@/components/shapes/Point';
import { Area } from '@/components/shapes/Area';
import { getDataMarginBounds, ScaleLinear } from 'eazychart-core/src';
import {
  LineConfig,
  RawData,
  AreaConfig,
  MarkerConfig,
  AnimationOptions,
  ChartPadding,
  GridConfig,
  AxisConfig,
  Position,
  Dimensions,
  Direction,
  RawDatum,
  AreaData,
  AreaCurve,
} from 'eazychart-core/src/types';

export interface LineErrorMarginChartProps extends SVGAttributes<SVGGElement> {
  line: LineConfig;
  swapAxis?: boolean;
  data: RawData;
  area?: Partial<AreaConfig>;
  marker?: MarkerConfig;
  animationOptions?: AnimationOptions;
  padding?: ChartPadding;
  grid?: GridConfig;
  isRTL?: boolean;
  xAxis?: AxisConfig<Position.BOTTOM | Position.TOP>;
  yAxis?: AxisConfig<Position.LEFT | Position.RIGHT>;
  dimensions?: Partial<Dimensions>;
  errorMargins?: {
    positive: string; // in percent [0..1]
    negative: string; // in percent [0..1]
  };
  scopedSlots?: {
    TooltipComponent?: FC<TooltipProps>;
  };
}

export const LineErrorMarginChart: FC<LineErrorMarginChartProps> = ({
  swapAxis = false,
  data,
  line = {
    stroke: '#339999',
    strokeWidth: 2,
    curve: 'curveBasis',
  },
  area = {
    fill: '#ef476f80',
  },
  marker = {
    hidden: false,
    radius: 5,
    color: '#FFF',
  },
  animationOptions = {
    easing: 'easeBack',
    duration: 400,
    delay: 0,
  },
  padding = {
    left: 100,
    bottom: 100,
    right: 100,
    top: 100,
  },
  grid = {
    directions: [Direction.HORIZONTAL, Direction.VERTICAL],
    color: '#a8a8a8',
  },
  xAxis = {
    domainKey: 'xValue',
  },
  yAxis = {
    domainKey: 'yValue',
  },
  errorMargins = { positive: 'positiveMargin', negative: 'negativeMargin' },
  isRTL = false,
  dimensions = {},
  scopedSlots = {
    TooltipComponent: Tooltip,
  },
}) => {
  const horizontalAxis = swapAxis ? yAxis : xAxis;
  const verticalAxis = swapAxis ? xAxis : yAxis;

  const [lowsestMarginValue, highestMarginValue] = useMemo(() => {
    const dataValues = data.map((datum) => datum[yAxis.domainKey] as number);
    const negativeMargins = data.map(
      (datum) => datum[errorMargins.negative] as number
    );
    const positiveMargins = data.map(
      (datum) => datum[errorMargins.positive] as number
    );
    return getDataMarginBounds(dataValues, negativeMargins, positiveMargins);
  }, [data, yAxis.domainKey, errorMargins]);

  const xScale = useMemo<ScaleLinear>(
    () =>
      new ScaleLinear({
        direction: Direction.HORIZONTAL,
        domainKey: horizontalAxis.domainKey,
        nice: horizontalAxis.nice || 0,
        reverse: isRTL,
      }),
    [isRTL, horizontalAxis]
  );
  const yScale = useMemo<ScaleLinear>(
    () =>
      new ScaleLinear({
        direction: Direction.VERTICAL,
        domainKey: verticalAxis.domainKey,
        nice: verticalAxis.nice || 0,
        minPadding: lowsestMarginValue,
        maxPadding: highestMarginValue,
      }),
    [verticalAxis, lowsestMarginValue, highestMarginValue]
  );

  return (
    <Chart
      dimensions={dimensions}
      rawData={data}
      scales={[xScale, yScale]}
      padding={padding}
      colors={[line.stroke]}
      animationOptions={animationOptions}
      scopedSlots={scopedSlots}
    >
      <Grid
        directions={grid.directions}
        color={grid.color}
        xScale={xScale}
        yScale={yScale}
      />
      <Points
        xScale={xScale}
        yScale={yScale}
        scopedSlots={{
          default: ({ scaledData }) => {
            const lineAreaData = scaledData.map((d, idx) => {
              const datum: RawDatum = data[idx];
              return {
                x: d.x,
                // @todo error margin data must be scaled
                y0: yScale.scale(
                  (datum[yAxis.domainKey] as number) *
                    (1 - Number(datum[errorMargins.negative]))
                ),
                y1: yScale.scale(
                  (datum[yAxis.domainKey] as number) *
                    (1 + Number(datum[errorMargins.positive]))
                ),
              };
            });
            return (
              <g className="ez-line-error-margin">
                <Area
                  shapeData={lineAreaData as AreaData}
                  curve={line.curve as AreaCurve}
                  beta={line.beta}
                  fill={area.fill}
                />
                <LinePath
                  shapeData={scaledData}
                  curve={line.curve}
                  beta={line.beta}
                  stroke={line.stroke}
                  strokeWidth={line.strokeWidth}
                />
                {!marker.hidden &&
                  scaledData.map((pointDatum) => {
                    return (
                      <Point
                        key={pointDatum.id}
                        shapeDatum={pointDatum}
                        r={marker.radius}
                        fill={marker.color}
                        strokeWidth={line.strokeWidth}
                      />
                    );
                  })}
              </g>
            );
          },
        }}
      />
      <Axis
        position={horizontalAxis.position || Position.BOTTOM}
        aScale={xScale}
        title={horizontalAxis.title}
        titleAlign={horizontalAxis.titleAlign}
        tickLength={horizontalAxis.tickLength}
        tickCount={horizontalAxis.tickCount}
        tickSize={horizontalAxis.tickLength}
        tickFormat={horizontalAxis.tickFormat}
      />
      <Axis
        position={
          verticalAxis.position || (isRTL ? Position.RIGHT : Position.LEFT)
        }
        aScale={yScale}
        title={verticalAxis.title}
        titleAlign={verticalAxis.titleAlign}
        tickLength={verticalAxis.tickLength}
        tickCount={verticalAxis.tickCount}
        tickSize={verticalAxis.tickSize}
        tickFormat={verticalAxis.tickFormat}
      />
    </Chart>
  );
};

// packages/ez-vue/src/recipes/line/LineErrorMarginChart.tsx
import Vue, { PropType } from 'vue';
import Component from 'vue-class-component';
import { Prop } from 'vue-property-decorator';
import { getDataMarginBounds, ScaleLinear } from 'eazychart-core/src';
import {
  RawData,
  Dimensions,
  LineConfig,
  AreaConfig,
  MarkerConfig,
  AnimationOptions,
  ChartPadding,
  GridConfig,
  Direction,
  AxisConfig,
  Position,
  PointDatum,
  AreaData,
  AreaCurve,
} from 'eazychart-core/src/types';
import Chart from '@/components/Chart';
import Axis from '@/components/scales/Axis';
import Legend from '@/components/addons/legend/Legend';
import Tooltip from '@/components/addons/tooltip/Tooltip';
import Grid from '@/components/scales/grid/Grid';
import Points from '@/components/Points';
import LinePath from '@/components/shapes/LinePath';
import Point from '@/components/shapes/Point';
import Area from '@/components/shapes/Area';

@Component({
  components: {
    Chart,
    Grid,
    LinePath,
    Points,
    Point,
    Axis,
    Legend,
    Tooltip,
  },
})
export default class LineErrorMarginChart extends Vue {
  @Prop({
    type: Boolean,
    default() {
      return true;
    },
  })
  private readonly swapAxis!: boolean;

  @Prop({
    type: Array as PropType<RawData>,
    required: true,
  })
  private readonly data!: RawData;

  @Prop({
    type: Object as PropType<Partial<Dimensions>>,
    default() {
      return {};
    },
  })
  private readonly dimensions!: Partial<Dimensions>;

  @Prop({
    type: Object as PropType<LineConfig>,
    default() {
      return {
        color: '#339999',
        lineWidth: 2,
        curve: 'curveLinear',
      };
    },
  })
  private readonly line!: LineConfig;

  @Prop({
    type: Object as PropType<AreaConfig>,
    default() {
      return {
        fill: '#ef476f80',
      };
    },
  })
  private readonly area!: AreaConfig;

  @Prop({
    type: Object as PropType<MarkerConfig>,
    default() {
      return {
        hidden: true,
        radius: 5,
        color: '#FFF',
      };
    },
  })
  private readonly marker!: MarkerConfig;

  @Prop({
    type: Object as PropType<AnimationOptions>,
    default() {
      return {
        easing: 'easeBack',
        duration: 400,
        delay: 0,
      };
    },
  })
  private readonly animationOptions!: AnimationOptions;

  @Prop({
    type: Object as PropType<ChartPadding>,
    default() {
      return {
        left: 100,
        bottom: 100,
        right: 100,
        top: 100,
      };
    },
  })
  private readonly padding!: ChartPadding;

  @Prop({
    type: Object as PropType<GridConfig>,
    default() {
      return {
        directions: [Direction.HORIZONTAL, Direction.VERTICAL],
        color: '#a8a8a8',
      };
    },
  })
  private readonly grid!: GridConfig;

  @Prop({
    type: Object as PropType<AxisConfig<Position.BOTTOM | Position.TOP>>,
    default() {
      return {
        domainKey: 'xValue',
      };
    },
  })
  private readonly xAxis!: AxisConfig<Position.BOTTOM | Position.TOP>;

  @Prop({
    type: Object as PropType<AxisConfig<Position.LEFT | Position.RIGHT>>,
    default() {
      return {
        domainKey: 'yValue',
      };
    },
  })
  private readonly yAxis!: AxisConfig<Position.LEFT | Position.RIGHT>;

  @Prop({
    type: Object as PropType<{ negative: string; positive: string }>,
    default() {
      return {
        positive: 'positiveMargin',
        negative: 'negativeMargin',
      };
    },
  })
  private readonly errorMargins!: { negative: string; positive: string };

  @Prop({
    type: Boolean,
    default() {
      return false;
    },
  })
  private readonly isRTL!: boolean;

  get horizontalAxis() {
    return this.swapAxis ? this.yAxis : this.xAxis;
  }

  get verticalAxis() {
    return this.swapAxis ? this.xAxis : this.yAxis;
  }

  private xScale!: ScaleLinear;

  private yScale!: ScaleLinear;

  created() {
    const { data, yAxis, errorMargins } = this;
    const dataValues = data.map((datum) => datum[yAxis.domainKey] as number);
    const negativeMargins = data.map(
      (datum) => datum[errorMargins.negative] as number,
    );
    const positiveMargins = data.map(
      (datum) => datum[errorMargins.positive] as number,
    );
    const [lowsestMarginValue, highestMarginValue] = getDataMarginBounds(
      dataValues,
      negativeMargins,
      positiveMargins,
    );
    this.xScale = new ScaleLinear({
      direction: Direction.HORIZONTAL,
      domainKey: this.horizontalAxis.domainKey,
      nice: this.horizontalAxis.nice || 0,
      reverse: this.isRTL,
    });

    this.yScale = new ScaleLinear({
      direction: Direction.VERTICAL,
      domainKey: this.verticalAxis.domainKey,
      nice: this.verticalAxis.nice || 0,
      minPadding: lowsestMarginValue,
      maxPadding: highestMarginValue,
    });
  }

  render() {
    const {
      xScale,
      yScale,
      horizontalAxis,
      verticalAxis,
      errorMargins,
      data,
      line,
      area,
      marker,
      padding,
      animationOptions,
      grid,
      isRTL,
      $scopedSlots,
      dimensions,
    } = this;

    return (
      <Chart
        dimensions={dimensions}
        rawData={data}
        scales={[xScale, yScale]}
        padding={padding}
        colors={[line.stroke]}
        animationOptions={animationOptions}
        scopedSlots={$scopedSlots}
        isRTL={isRTL}
      >
        <Grid
          directions={grid.directions}
          color={grid.color}
          xScale={xScale}
          yScale={yScale}
        />
        <Points
          xScale={xScale}
          yScale={yScale}
          scopedSlots={{
            default: ({ scaledData }: { scaledData: PointDatum[] }) => {
              const lineAreaData = scaledData.map((d, idx) => {
                const datum = data[idx];
                return {
                  x: d.x,
                  y0: yScale.scale(
                    (datum[verticalAxis.domainKey] as number)
                      * (1 - Number(datum[errorMargins.negative])),
                  ),
                  y1: yScale.scale(
                    (datum[verticalAxis.domainKey] as number)
                      * (1 + Number(datum[errorMargins.positive])),
                  ),
                };
              });

              return (
                <g class="ez-line-error-margin">
                  <Area
                    shapeData={lineAreaData as AreaData}
                    curve={line.curve as AreaCurve}
                    beta={line.beta}
                    fill={area.fill}
                  />
                  <LinePath
                    shapeData={scaledData}
                    curve={line.curve}
                    beta={line.beta}
                    stroke={line.stroke}
                    strokeWidth={line.strokeWidth}
                  />
                  {!marker.hidden
                    && scaledData.map((pointDatum) => (
                      <Point
                        key={pointDatum.id}
                        shapeDatum={pointDatum}
                        r={marker.radius}
                        fill={marker.color}
                        strokeWidth={line.strokeWidth}
                      />
                    ))}
                </g>
              );
            },
          }}
        />
        <Axis
          position={horizontalAxis.position || Position.BOTTOM}
          aScale={xScale}
          title={horizontalAxis.title}
          titleAlign={horizontalAxis.titleAlign}
          tickLength={horizontalAxis.tickLength}
          tickCount={horizontalAxis.tickCount}
          tickSize={horizontalAxis.tickLength}
          tickFormat={horizontalAxis.tickFormat}
        />
        <Axis
          position={
            verticalAxis.position
            || (isRTL ? Position.RIGHT : Position.LEFT)
          }
          aScale={yScale}
          title={verticalAxis.title}
          titleAlign={verticalAxis.titleAlign}
          tickLength={verticalAxis.tickLength}
          tickCount={verticalAxis.tickCount}
          tickSize={verticalAxis.tickLength}
          tickFormat={verticalAxis.tickFormat}
        />
      </Chart>
    );
  }
}
