// packages/ez-react/src/components/shapes/AreaPath.tsx
import React, { FC, SVGAttributes, useMemo } from 'react';
import { AreaCurve, AreaData } from 'eazychart-core/src/types';
import { defaultColor, generateAreaPath } from 'eazychart-core/src';
import { useAnimation } from '../../lib/use-animation';
import { useChart } from '@/lib/use-chart';

export interface AreaPathProps extends SVGAttributes<SVGPathElement> {
  shapeData?: AreaData;
  curve?: AreaCurve;
  beta?: number;
}

export const AreaPath: FC<AreaPathProps> = ({
  shapeData = [],
  curve = 'curveLinear',
  beta,
  fill = defaultColor,
  opacity = 1,
  ...rest
}) => {
  const { animationOptions } = useChart();
  const dataPath = useMemo(
    () => generateAreaPath(shapeData, curve, beta),
    [shapeData, curve, beta]
  );
  const currentData =
    useAnimation(dataPath, '', animationOptions, [curve]) || '';
  return (
    <path
      d={currentData}
      stroke={'none'}
      strokeWidth={0}
      fill={fill}
      opacity={opacity}
      strokeLinejoin={'round'}
      strokeLinecap={'round'}
      {...rest}
      className="ez-area-path"
    />
  );
};

// packages/ez-vue/src/components/shapes/AreaPath.tsx
import { PropType } from 'vue';
import Component, { mixins } from 'vue-class-component';
import { ChartContext, AreaCurve, AreaData } from 'eazychart-core/src/types';
import { InjectReactive, Prop } from 'vue-property-decorator';
import { defaultColor, generateAreaPath } from 'eazychart-core/src';
import AnimationMixin from '@/lib/AnimationMixin';

@Component
export default class AreaPath extends mixins(AnimationMixin) {
  @InjectReactive('chart')
  private chart!: ChartContext;

  @Prop({
    type: Array as PropType<AreaData>,
    default() {
      return [];
    },
  })
  private readonly shapeData!: AreaData;

  @Prop({
    type: String as PropType<AreaCurve>,
    default() {
      return 'curveLinear';
    },
  })
  private readonly curve!: AreaCurve;

  @Prop({
    type: Number,
  })
  private readonly beta!: number;

  @Prop({
    type: String,
    default() {
      return defaultColor;
    },
  })
  private readonly fill!: string;

  @Prop({
    type: String,
    default() {
      return 1;
    },
  })
  private readonly opacity!: string;

  private currentShapeData = '';

  get animationArguments() {
    const path = generateAreaPath(this.shapeData, this.curve, this.beta);
    return {
      from: this.currentShapeData,
      to: path,
      options: this.chart.animationOptions,
      onUpdate: (v: string) => (this.currentShapeData = v),
      dependencies: ['shapeData', 'curve', 'beta'],
    };
  }

  render() {
    const { currentShapeData, fill, opacity } = this;
    return (
      <path
        d={currentShapeData}
        stroke={'none'}
        stroke-width={0}
        fill={fill}
        opacity={opacity}
        stroke-linejoin={'round'}
        stroke-linecap={'round'}
        class="ez-area-path"
      />
    );
  }
}
