// packages/ez-react/src/components/shapes/Bubble.tsx
import React, { FC } from 'react';
import { defaultPointDatum } from 'eazychart-core/src';
import { Point, PointProps } from './Point';

export interface BubbleProps extends PointProps {
  fill?: string;
}

export const Bubble: FC<BubbleProps> = ({
  shapeDatum = defaultPointDatum,
  fill,
  ...rest
}) => {
  return (
    <Point
      shapeDatum={shapeDatum}
      key={shapeDatum.id}
      r={shapeDatum.radius}
      fill={fill}
      {...rest}
    />
  );
};

// packages/ez-vue/src/components/shapes/Bubble.tsx
import Vue, { PropType } from 'vue';
import Component from 'vue-class-component';
import { PointDatum } from 'eazychart-core/src/types';
import { defaultBubbleDatum } from 'eazychart-core/src';
import { Prop } from 'vue-property-decorator';
import Point from './Point';

@Component
export default class Bubble extends Vue {
  @Prop({
    type: Object as PropType<PointDatum>,
    default() {
      return defaultBubbleDatum;
    },
  })
  private readonly shapeDatum!: PointDatum;

  @Prop({
    type: String,
    default: null,
  })
  private readonly fill!: string;

  render() {
    const {
      shapeDatum,
      fill,
    } = this;
    return (
      <Point shapeDatum={shapeDatum} key={shapeDatum.id} r={shapeDatum.radius} fill={fill} />
    );
  }
}
