// packages/ez-vue/src/components/addons/legend/LegendProvider.tsx
import Vue from 'vue';
import Component from 'vue-class-component';
import Fragment from '@/lib/Fragment';

@Component
export default class LegendProvider extends Vue {
  render() {
    const DefaultSlot = this.$scopedSlots.default
      ? this.$scopedSlots.default({})
      : null;
    const LegendOverride = this.$scopedSlots.Legend
      ? this.$scopedSlots.Legend({})
      : null;
    return (
      <Fragment type="div" name="filter" ref="legendFragment">
        {DefaultSlot}
        {LegendOverride}
      </Fragment>
    );
  }
}

// packages/ez-react/src/components/addons/legend/LegendProvider.tsx
import { Fragment } from '@/lib/Fragment';
import React, { FC } from 'react';

export interface LegendProviderProps {
  Legend?: JSX.Element;
  isWrapped?: boolean;
}

export const LegendProvider: FC<LegendProviderProps> = ({
  Legend,
  children,
  isWrapped = true,
}) => {
  return isWrapped ? (
    <Fragment type="div" name="filter">
      {children}
      {Legend}
    </Fragment>
  ) : (
    <>
      {children}
      {Legend}
    </>
  );
};
