// packages/ez-vue/src/recipes/pie/RadialChart.tsx
import Vue, { PropType } from 'vue';
import Component from 'vue-class-component';
import {
  AnimationOptions,
  ChartPadding,
  Direction,
  RawData,
  RadialConfig,
  Dimensions,
} from '@ez/core/src/types';
import { Prop } from 'vue-property-decorator';
import { ScaleLinear } from '@ez/core/src';
import Chart from '@/components/Chart';
import Legend from '@/components/addons/legend/Legend';
import Tooltip from '@/components/addons/tooltip/Tooltip';
import Arcs from '@/components/Arcs';

@Component({
  components: {
    Chart,
    Arcs,
    Legend,
    Tooltip,
  },
})
export default class RadialChart extends Vue {
  @Prop({
    type: Array as PropType<RawData>,
    required: true,
  })
  private readonly rawData!: RawData;

  @Prop({
    type: Object as PropType<Dimensions>,
    default() {
      return {};
    },
  })
  private readonly dimensions!: Partial<Dimensions>;

  @Prop({
    type: Array,
    default() {
      return ['#339999', '#993399', '#333399'];
    },
  })
  private readonly colors!: string[];

  @Prop({
    type: Object as PropType<AnimationOptions>,
    default() {
      return {
        easing: 'easeBack',
        duration: 400,
        delay: 0,
      };
    },
  })
  private readonly animationOptions!: AnimationOptions;

  @Prop({
    type: Object as PropType<ChartPadding>,
    default() {
      return {
        left: 100,
        bottom: 100,
        right: 100,
        top: 100,
      };
    },
  })
  private readonly padding!: ChartPadding;

  @Prop({
    type: String,
    default: 'value',
  })
  private readonly domainKey!: string;

  @Prop({
    type: Object as PropType<RadialConfig>,
    default() {
      return {
        cornerRadius: 0,
        stroke: '#FFF',
        strokeWidth: 0,
        sortValues: null,
        spacing: 0,
      };
    },
  })
  private readonly arc!: RadialConfig;

  @Prop({
    type: Function as PropType<(dimensions: Dimensions) => void>,
    required: false,
  })
  private readonly onResize?: (dimensions: Dimensions) => void;

  private scale!: ScaleLinear;

  created() {
    this.scale = new ScaleLinear({
      direction: Direction.HORIZONTAL,
      domainKey: this.domainKey,
      range: [0, 2 * Math.PI],
    });
  }

  render() {
    const {
      scale,
      rawData,
      padding,
      colors,
      animationOptions,
      arc,
      onResize,
      $scopedSlots,
      dimensions,
    } = this;

    const scopedSlots = {
      Legend: $scopedSlots.Legend ? $scopedSlots.Legend : () => <Legend />,
      Tooltip: $scopedSlots.Tooltip,
    };

    return (
      <Chart
        dimensions={dimensions}
        rawData={rawData}
        scales={[scale]}
        padding={padding}
        colors={colors}
        animationOptions={animationOptions}
        scopedSlots={scopedSlots}
        onResize={onResize}
      >
        <Arcs
          arcScale={scale}
          cornerRadius={arc.cornerRadius}
          stroke={arc.stroke}
          strokeWidth={arc.strokeWidth}
          spacing={arc.spacing}
        />
      </Chart>
    );
  }
}

// packages/ez-react/src/recipes/pie/RadialChart.tsx
import React, { FC, SVGAttributes, useMemo } from 'react';
import {
  Direction,
  RawData,
  AnimationOptions,
  ChartPadding,
  Dimensions,
  RadialConfig,
} from '@ez/core/src/types';
import { TooltipProps, Tooltip } from '@/components/addons/tooltip/Tooltip';
import { Chart } from '@/components/Chart';
import { Legend, LegendPropsWithRef } from '@/components/addons/legend/Legend';
import { ScaleLinear } from '@ez/core/src';
import { Arcs } from '@/components/Arcs';

export interface RadialChartProps extends SVGAttributes<SVGGElement> {
  rawData: RawData;
  colors?: string[];
  animationOptions?: AnimationOptions;
  padding?: ChartPadding;
  domainKey?: string;
  index?: number;
  arc?: RadialConfig;
  dimensions?: Partial<Dimensions>;
  scopedSlots?: {
    LegendComponent: React.FC<LegendPropsWithRef>;
    TooltipComponent: React.FC<TooltipProps>;
  };
  onResize?: (dimensions: Dimensions) => void;
}

export const RadialChart: FC<RadialChartProps> = ({
  rawData,
  colors = ['#339999', '#993399', '#333399'],
  animationOptions = {
    easing: 'easeBack',
    duration: 400,
    delay: 0,
  },
  padding = {
    left: 100,
    bottom: 100,
    right: 100,
    top: 100,
  },
  domainKey = 'value',
  arc = {
    cornerRadius: 0,
    stroke: '#FFF',
    strokeWidth: 0,
    spacing: 0,
  },
  dimensions = {},
  scopedSlots = {
    LegendComponent: Legend,
    TooltipComponent: Tooltip,
  },
  onResize,
}) => {
  const scale = useMemo<ScaleLinear>(
    () =>
      new ScaleLinear({
        direction: Direction.HORIZONTAL,
        range: [0, Math.PI * 2],
        domainKey,
      }),
    [domainKey]
  );
  return (
    <>
      <Chart
        dimensions={dimensions}
        rawData={rawData}
        scales={[scale]}
        padding={padding}
        colors={colors}
        animationOptions={animationOptions}
        scopedSlots={scopedSlots}
        onResize={onResize}
      >
        <Arcs arcScale={scale} {...arc} />
      </Chart>
    </>
  );
};
