// packages/ez-vue/src/components/shapes/Arc.tsx
import { PropType } from 'vue';
import Component, { mixins } from 'vue-class-component';
import { ChartContext, ArcDatum, TooltipContext } from 'eazychart-core/src/types';
import {
  Inject,
  InjectReactive,
  Prop,
} from 'vue-property-decorator';
import { generateArc } from 'eazychart-core/src';
import AnimationMixin from '@/lib/AnimationMixin';

@Component
export default class Arc extends mixins(AnimationMixin) {
  @Inject('tooltip')
  private tooltip!: TooltipContext;

  @InjectReactive('chart')
  private chart!: ChartContext;

  @Prop({
    type: Object as PropType<ArcDatum>,
    required: true,
  })
  private readonly shapeDatum!: ArcDatum;

  @Prop({
    type: Number,
    required: true,
  })
  private readonly innerRadius!: number;

  @Prop({
    type: Number,
    required: true,
  })
  private readonly outerRadius!: number;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly cornerRadius!: number;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly padAngle!: number;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly padRadius!: number;

  @Prop({
    type: String,
  })
  private readonly stroke!: string;

  @Prop({
    type: Number,
  })
  private readonly strokeWidth!: number;

  private currentShapeDatum: ArcDatum = {
    ...this.shapeDatum,
    color: '#FFF',
    startAngle: this.shapeDatum?.startAngle,
    endAngle: this.shapeDatum?.startAngle,
  };

  // The following is a workaround to make unit tests work
  // It seems in test environement, the props are undefined
  data(): { currentShapeDatum: ArcDatum } {
    return {
      currentShapeDatum: {
        ...this.shapeDatum,
        color: '#FFF',
        startAngle: this.shapeDatum.startAngle,
        endAngle: this.shapeDatum.startAngle,
      },
    };
  }

  handleMouseOver(event: MouseEvent) {
    this.tooltip.showTooltip(this.shapeDatum, event);
  }

  handleMouseMove(event: MouseEvent) {
    this.tooltip.moveTooltip(this.shapeDatum, event);
  }

  handleMouseLeave(event: MouseEvent) {
    this.tooltip.hideTooltip(this.shapeDatum, event);
  }

  handleClick(event: MouseEvent) {
    this.chart.onShapeClick && this.chart.onShapeClick(this.shapeDatum, event);
  }

  get animationArguments() {
    return {
      from: this.currentShapeDatum,
      to: this.shapeDatum,
      options: this.chart.animationOptions,
      onUpdate: (v: ArcDatum) => (this.currentShapeDatum = v),
      dependencies: ['shapeDatum'],
    };
  }

  get path() {
    return generateArc(
      this.currentShapeDatum,
      this.outerRadius,
      this.innerRadius,
      this.cornerRadius,
      this.padAngle,
      this.padRadius,
    );
  }

  render() {
    const {
      path,
      shapeDatum,
      stroke,
      strokeWidth,
      handleMouseOver,
      handleMouseMove,
      handleMouseLeave,
      handleClick,
    } = this;
    return (
      <path
        d={path || ''}
        fill={shapeDatum.color}
        stroke={stroke || shapeDatum.color}
        stroke-width={strokeWidth}
        onMouseover={handleMouseOver}
        onMousemove={handleMouseMove}
        onMouseleave={handleMouseLeave}
        onClick={handleClick}
        class="ez-arc"
        data-testid="ez-arc"
      />
    );
  }
}

// packages/ez-react/src/components/shapes/Arc.tsx
import React, { FC, MouseEventHandler, SVGAttributes, useMemo } from 'react';
import { useChart } from '@/lib/use-chart';
import { useAnimation } from '@/lib/use-animation';
import { ArcDatum, ArcConfig } from 'eazychart-core/src/types';
import { generateArc } from 'eazychart-core/src';
import { useTooltip } from '../addons/tooltip/use-tooltip';

export interface ArcProps
  extends ArcConfig,
    Omit<SVGAttributes<SVGPathElement>, 'stroke' | 'strokeWidth'> {
  shapeDatum: ArcDatum;
  innerRadius: number;
  outerRadius: number;
}

export const Arc: FC<ArcProps> = ({
  shapeDatum,
  innerRadius,
  outerRadius,
  cornerRadius = 0,
  padAngle = 0,
  padRadius = 0,
  stroke,
  ...rest
}) => {
  const { showTooltip, hideTooltip, moveTooltip } = useTooltip();
  const { animationOptions, onShapeClick } = useChart();
  const currentShapeData = useAnimation(
    shapeDatum,
    {
      ...shapeDatum,
      color: '#FFF',
      startAngle: shapeDatum.startAngle,
      endAngle: shapeDatum.startAngle,
    },
    animationOptions
  );

  const path = useMemo(
    () =>
      generateArc(
        currentShapeData,
        outerRadius,
        innerRadius,
        cornerRadius,
        padAngle,
        padRadius
      ),
    [
      currentShapeData,
      outerRadius,
      innerRadius,
      cornerRadius,
      padAngle,
      padRadius,
    ]
  );

  const handleMouseOver: MouseEventHandler<SVGPathElement> = (event) => {
    showTooltip(shapeDatum, event as any as MouseEvent);
  };

  const handleMouseMove: MouseEventHandler<SVGPathElement> = (event) => {
    moveTooltip(shapeDatum, event as any as MouseEvent);
  };

  const handleMouseLeave: MouseEventHandler<SVGPathElement> = (event) => {
    hideTooltip(shapeDatum, event as any as MouseEvent);
  };

  const handleClick: MouseEventHandler<SVGPathElement> = (event) => {
    onShapeClick && onShapeClick(shapeDatum, event as any as MouseEvent);
  };

  return (
    <path
      key={shapeDatum.id}
      d={path || ''}
      fill={shapeDatum.color}
      stroke={stroke || shapeDatum.color}
      {...rest}
      onMouseOver={handleMouseOver}
      onMouseMove={handleMouseMove}
      onMouseLeave={handleMouseLeave}
      onClick={handleClick}
      data-testid="ez-arc"
      className="ez-arc"
    />
  );
};
