// packages/ez-vue/src/components/shapes/Bar.tsx
import { PropType } from 'vue';
import Component, { mixins } from 'vue-class-component';
import {
  ChartContext,
  RectangleDatum,
  TooltipContext,
} from 'eazychart-core/src/types';
import { defaultRectangleDatum } from 'eazychart-core/src';
import {
  Inject, InjectReactive, Prop,
} from 'vue-property-decorator';
import AnimationMixin from '@/lib/AnimationMixin';

@Component
export default class Bar extends mixins(AnimationMixin) {
  @Inject('tooltip')
  private tooltip!: TooltipContext;

  @InjectReactive('chart')
  private chart!: ChartContext;

  @Prop({
    type: Object as PropType<RectangleDatum>,
    default() {
      return defaultRectangleDatum;
    },
  })
  private readonly shapeDatum!: RectangleDatum;

  private currentShapeDatum: RectangleDatum = defaultRectangleDatum;

  handleMouseOver(event: MouseEvent) {
    this.tooltip.showTooltip(this.shapeDatum, event);
  }

  handleMouseMove(event: MouseEvent) {
    this.tooltip.moveTooltip(this.shapeDatum, event);
  }

  handleMouseLeave(event: MouseEvent) {
    this.tooltip.hideTooltip(this.shapeDatum, event);
  }

  handleClick(event: MouseEvent) {
    this.chart.onShapeClick && this.chart.onShapeClick(this.shapeDatum, event);
  }

  get animationArguments() {
    return {
      from: this.currentShapeDatum,
      to: this.shapeDatum,
      options: this.chart.animationOptions,
      onUpdate: (v: RectangleDatum) => (this.currentShapeDatum = v),
      dependencies: ['shapeDatum'],
    };
  }

  render() {
    const {
      currentShapeDatum,
      handleMouseOver,
      handleMouseMove,
      handleMouseLeave,
      handleClick,
    } = this;
    const {
      color, x, y, width, height,
    } = currentShapeDatum;
    return (
      <rect
        class="ez-bar"
        fill={color}
        x={x}
        y={y}
        width={width}
        height={height}
        onMouseover={handleMouseOver}
        onMousemove={handleMouseMove}
        onMouseleave={handleMouseLeave}
        onClick={handleClick}
        data-testid="ez-bar"
      />
    );
  }
}

// packages/ez-react/src/components/shapes/Bar.tsx
import React, { FC, MouseEventHandler, SVGAttributes } from 'react';
import { RectangleDatum } from 'eazychart-core/src/types';
import { defaultRectangleDatum } from 'eazychart-core/src';
import { useAnimation } from '@/lib/use-animation';
import { useTooltip } from '@/components/addons/tooltip/use-tooltip';
import { useChart } from '@/lib/use-chart';

export interface BarProps extends SVGAttributes<SVGRectElement> {
  shapeDatum?: RectangleDatum;
}

export const Bar: FC<BarProps> = ({
  shapeDatum = defaultRectangleDatum,
  ...rest
}) => {
  const { animationOptions, onShapeClick } = useChart();
  const { showTooltip, hideTooltip, moveTooltip } = useTooltip();
  const currentShapeDatum = useAnimation(
    shapeDatum,
    defaultRectangleDatum,
    animationOptions
  );
  const { x, y, width, height, color } = currentShapeDatum;

  const handleMouseOver: MouseEventHandler<SVGRectElement> = (event) => {
    showTooltip(shapeDatum, event as any as MouseEvent);
  };

  const handleMouseMove: MouseEventHandler<SVGRectElement> = (event) => {
    moveTooltip(shapeDatum, event as any as MouseEvent);
  };

  const handleMouseLeave: MouseEventHandler<SVGRectElement> = (event) => {
    hideTooltip(shapeDatum, event as any as MouseEvent);
  };

  const handleClick: MouseEventHandler<SVGRectElement> = (event) => {
    onShapeClick && onShapeClick(shapeDatum, event as any as MouseEvent);
  };

  return (
    <rect
      fill={color}
      x={x}
      y={y}
      width={width}
      height={height}
      onMouseOver={handleMouseOver}
      onMouseMove={handleMouseMove}
      onMouseLeave={handleMouseLeave}
      onClick={handleClick}
      {...rest}
      data-testid="ez-bar"
      className="ez-bar"
    />
  );
};
