// packages/ez-vue/src/components/shapes/LinePath.tsx
import { PropType } from 'vue';
import Component, { mixins } from 'vue-class-component';
import { ChartContext, PointDatum, LineCurve } from 'eazychart-core/src/types';
import { InjectReactive, Prop } from 'vue-property-decorator';
import { defaultColor, generateLinePath } from 'eazychart-core/src';
import AnimationMixin from '@/lib/AnimationMixin';

@Component
export default class LinePath extends mixins(AnimationMixin) {
  @InjectReactive('chart')
  private chart!: ChartContext;

  @Prop({
    type: Array as PropType<PointDatum[]>,
    default() {
      return [];
    },
  })
  private readonly shapeData!: PointDatum[];

  @Prop({
    type: String as PropType<LineCurve>,
    default() {
      return 'curveLinear';
    },
  })
  private readonly curve!: LineCurve;

  @Prop({
    type: Number,
  })
  private readonly beta!: number;

  @Prop({
    type: String,
    default() {
      return defaultColor;
    },
  })
  private readonly stroke!: string;

  @Prop({
    type: Number,
    default() {
      return 1;
    },
  })
  private readonly strokeWidth!: number;

  private currentShapeData = '';

  get animationArguments() {
    const path = generateLinePath(this.shapeData, this.curve, this.beta);
    return {
      from: this.currentShapeData,
      to: path,
      options: this.chart.animationOptions,
      onUpdate: (v: string) => this.currentShapeData = v,
      dependencies: ['shapeData', 'curve', 'beta'],
    };
  }

  render() {
    const { currentShapeData, stroke, strokeWidth } = this;
    return <path
      d={currentShapeData}
      stroke={stroke}
      stroke-width={strokeWidth}
      fill="none"
      stroke-linejoin={'round'}
      stroke-linecap={'round'}
      class="ez-line"
      data-testid="ez-line"
    />;
  }
}

// packages/ez-react/src/components/shapes/LinePath.tsx
import React, { FC, SVGAttributes, useMemo } from 'react';
import { LineData, LineCurve } from 'eazychart-core/src/types';
import { defaultColor, generateLinePath } from 'eazychart-core/src';
import { useAnimation } from '@/lib/use-animation';
import { useChart } from '@/lib/use-chart';

export interface LinePathProps extends SVGAttributes<SVGPathElement> {
  shapeData?: LineData;
  curve?: LineCurve;
  beta?: number;
}

export const LinePath: FC<LinePathProps> = ({
  shapeData = [],
  curve = 'curveLinear',
  beta,
  stroke = defaultColor,
  strokeWidth = 1,
  ...rest
}) => {
  const { animationOptions } = useChart();
  const dataPath = useMemo(
    () => generateLinePath(shapeData, curve, beta),
    [shapeData, curve, beta]
  );
  const currentData =
    useAnimation(dataPath, '', animationOptions, [curve]) || '';
  return (
    <path
      d={currentData}
      stroke={stroke}
      strokeWidth={strokeWidth}
      fill="none"
      strokeLinejoin={'round'}
      strokeLinecap={'round'}
      {...rest}
      className="ez-line"
      data-testid="ez-line"
    />
  );
};
