// packages/ez-vue/src/components/shapes/MapPath.tsx
import { PropType } from 'vue';
import Component, { mixins } from 'vue-class-component';
import {
  ChartContext,
  GeoFeatureDatum,
  GeoProjectionCenter,
  GeoProjectionType,
  TooltipContext,
} from 'eazychart-core/src/types';
import { Inject, InjectReactive, Prop } from 'vue-property-decorator';
import { defaultColor, generateGeoFeaturePath } from 'eazychart-core/src';
import AnimationMixin from '@/lib/AnimationMixin';

@Component
export default class MapPath extends mixins(AnimationMixin) {
  @InjectReactive('chart')
  private chart!: ChartContext;

  @Inject('tooltip')
  private tooltip!: TooltipContext;

  @Prop({
    type: Object as PropType<GeoFeatureDatum>,
  })
  private readonly shapeDatum!: GeoFeatureDatum;

  @Prop({
    type: String as PropType<GeoProjectionType>,
    default() {
      return 'geoMercator';
    },
  })
  private readonly projectionType!: GeoProjectionType;

  @Prop({
    type: Object as PropType<GeoProjectionCenter>,
    required: true,
  })
  private readonly projectionCenter!: GeoProjectionCenter;

  @Prop({
    type: String,
    default() {
      return defaultColor;
    },
  })
  private readonly stroke!: string;

  @Prop({
    type: Number,
    default() {
      return 1;
    },
  })
  private readonly strokeWidth!: number;

  @Prop({
    type: String,
    default() {
      return defaultColor;
    },
  })
  private readonly fill!: string;

  private currentShapeData = '';

  handleMouseOver(event: MouseEvent) {
    this.tooltip.showTooltip(this.shapeDatum, event);
  }

  handleMouseMove(event: MouseEvent) {
    this.tooltip.moveTooltip(this.shapeDatum, event);
  }

  handleMouseLeave(event: MouseEvent) {
    this.tooltip.hideTooltip(this.shapeDatum, event);
  }

  get animationArguments() {
    const { shapeDatum, projectionType, projectionCenter } = this;
    const { dataPath } = generateGeoFeaturePath(
      shapeDatum,
      projectionType,
      projectionCenter,
    );

    return {
      from: this.currentShapeData,
      to: dataPath || '',
      options: this.chart.animationOptions,
      onUpdate: (v: string) => (this.currentShapeData = v),
      dependencies: ['shapeDatum', 'projectionType', 'projectionCenter'],
    };
  }

  render() {
    const {
      shapeDatum,
      currentShapeData,
      stroke,
      strokeWidth,
      fill,
      handleMouseOver,
      handleMouseMove,
      handleMouseLeave,
    } = this;

    return (
      <path
        d={currentShapeData}
        stroke={stroke || shapeDatum.color}
        stroke-width={strokeWidth}
        fill={shapeDatum.color || fill}
        stroke-linejoin={'round'}
        stroke-linecap={'round'}
        onMouseover={handleMouseOver}
        onMousemove={handleMouseMove}
        onMouseleave={handleMouseLeave}
        class="ez-map-path"
      />
    );
  }
}

// packages/ez-react/src/components/shapes/MapPath.tsx
import React, { FC, MouseEventHandler, SVGAttributes, useMemo } from 'react';
import {
  GeoProjection,
  GeoProjectionType,
  GeoProjectionCenter,
  GeoFeatureDatum,
} from 'eazychart-core/src/types';
import { defaultColor, generateGeoFeaturePath } from 'eazychart-core/src';
import { useAnimation } from '@/lib/use-animation';
import { useChart } from '@/lib/use-chart';
import { useTooltip } from '../addons/tooltip/use-tooltip';

export interface MapPathProps extends SVGAttributes<SVGPathElement> {
  shapeDatum: GeoFeatureDatum;
  projectionType?: GeoProjectionType;
  projection?: GeoProjection;
  projectionCenter: GeoProjectionCenter;
}

export const MapPath: FC<MapPathProps> = ({
  shapeDatum,
  projectionType = 'geoMercator',
  projectionCenter,
  stroke = defaultColor,
  fill = defaultColor,
  strokeWidth = 1,
  ...rest
}) => {
  const { showTooltip, hideTooltip, moveTooltip } = useTooltip();
  const { animationOptions } = useChart();

  const dataPath = useMemo(
    () => generateGeoFeaturePath(shapeDatum, projectionType, projectionCenter),
    [shapeDatum, projectionType, projectionCenter]
  ) as string;

  const currentData = useAnimation(dataPath || '', '', animationOptions) || '';

  const handleMouseOver: MouseEventHandler<SVGPathElement> = (event) => {
    showTooltip(shapeDatum, event as any as MouseEvent);
  };

  const handleMouseMove: MouseEventHandler<SVGPathElement> = (event) => {
    moveTooltip(shapeDatum, event as any as MouseEvent);
  };

  const handleMouseLeave: MouseEventHandler<SVGPathElement> = (event) => {
    hideTooltip(shapeDatum, event as any as MouseEvent);
  };

  if (!dataPath) return null;

  return (
    <path
      d={currentData}
      stroke={stroke || shapeDatum.color}
      strokeWidth={strokeWidth}
      fill={shapeDatum.color || fill}
      strokeLinejoin={'round'}
      strokeLinecap={'round'}
      onMouseOver={handleMouseOver}
      onMouseMove={handleMouseMove}
      onMouseLeave={handleMouseLeave}
      {...rest}
      className="ez-map-path"
    />
  );
};
