// packages/ez-react/src/components/Arcs.tsx
import React, { FC, SVGAttributes, useMemo } from 'react';
import { useChart } from '@/lib/use-chart';
import { Arc } from './shapes/Arc';
import { Dimensions, Point, PieConfig } from '@ez/core/src/types';
import { ScaleLinear, scaleArcData } from '@ez/core/src';

export interface ArcsProps
  extends PieConfig,
    Omit<SVGAttributes<SVGPathElement>, 'stroke' | 'strokeWidth'> {
  arcScale: ScaleLinear;
  getCenter?: (dimensions: Dimensions) => Point;
  getRadius?: (dimensions: Dimensions) => number;
  startAngle?: number;
  endAngle?: number;
  spacing?: number;
}

export const Arcs: FC<ArcsProps> = ({
  startAngle = 0,
  endAngle = 2 * Math.PI,
  arcScale,
  getCenter = ({ width, height }) => ({ x: width / 2, y: height / 2 }),
  getRadius = ({ width, height }) => Math.min(width, height) / 2,
  cornerRadius = 0,
  stroke,
  strokeWidth,
  sortValues,
  spacing = 0,
  ...rest
}) => {
  const { activeData, dimensions } = useChart();
  const { width, height } = dimensions;
  const center = getCenter({ width, height });
  const radius = getRadius({ width, height });

  const shapeData = useMemo(() => {
    return scaleArcData(activeData, arcScale, startAngle, sortValues);
  }, [activeData, arcScale, sortValues, startAngle]);

  return (
    <g
      transform={`translate(${center.x},${center.y})`}
      {...rest}
      className="ez-arcs"
    >
      {shapeData.map((shapeDatum, index) => {
        const arcWidth = radius / shapeData.length;
        const outerRadius = radius - index * arcWidth;
        const newArcWidth = arcWidth * (1 - spacing);
        const innerRadius = outerRadius - newArcWidth;
        return (
          <Arc
            key={shapeDatum.id}
            shapeDatum={shapeDatum}
            outerRadius={outerRadius}
            innerRadius={innerRadius}
            cornerRadius={cornerRadius}
            stroke={stroke}
            strokeWidth={strokeWidth}
          />
        );
      })}
    </g>
  );
};

// packages/ez-vue/src/components/Arcs.tsx
import Vue, { PropType } from 'vue';
import Component from 'vue-class-component';
import { ChartContext, Dimensions, Point } from '@ez/core/src/types';
import { InjectReactive, Prop } from 'vue-property-decorator';
import { ScaleLinear, scaleArcData } from '@ez/core/src';
import Arc from '@/components/shapes/Arc';

@Component({ components: { Arc } })
export default class Arcs extends Vue {
  @InjectReactive('chart')
  private chart!: ChartContext;

  @Prop({
    type: Object as PropType<ScaleLinear>,
    required: true,
  })
  private readonly arcScale!: ScaleLinear;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly spacing!: number;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly cornerRadius!: number;

  @Prop({
    type: String,
  })
  private readonly stroke!: string;

  @Prop({
    type: Number,
  })
  private readonly strokeWidth!: number;

  @Prop({
    type: Function,
    default: ({ width, height }: Dimensions) => ({
      x: width / 2,
      y: height / 2,
    }),
  })
  private readonly getCenter!: (dimensions: Dimensions) => Point;

  @Prop({
    type: Function,
    default: ({ width, height }: Dimensions) => Math.min(width, height) / 2,
  })
  private readonly getRadius!: (dimensions: Dimensions) => number;

  @Prop({
    type: Number,
    default: 0,
  })
  private readonly startAngle!: number;

  @Prop({
    type: Function,
  })
  private readonly sortValues!: undefined | ((a: number, b: number) => number);

  get radius() {
    return this.getRadius(this.chart.dimensions);
  }

  get center() {
    return this.getCenter(this.chart.dimensions);
  }

  get shapeData() {
    return scaleArcData(
      this.chart.activeData,
      this.arcScale,
      this.startAngle,
      this.sortValues,
    );
  }

  render() {
    const {
      shapeData,
      radius,
      center,
      cornerRadius,
      stroke,
      strokeWidth,
      spacing,
    } = this;

    return (
      <g transform={`translate(${center.x},${center.y})`} class="ez-arcs">
        {shapeData.map((shapeDatum, index) => {
          const arcWidth = radius / shapeData.length;
          const outerRadius = radius - index * arcWidth;
          const newArcWidth = arcWidth * (1 - spacing);
          const innerRadius = outerRadius - newArcWidth;
          return (
            <Arc
              key={shapeDatum.id}
              shapeDatum={shapeDatum}
              outerRadius={outerRadius}
              innerRadius={innerRadius}
              cornerRadius={cornerRadius}
              stroke={stroke}
              strokeWidth={strokeWidth}
            />
          );
        })}
      </g>
    );
  }
}
