// packages/ez-react/src/components/Bars.tsx
import React, { FC, SVGAttributes, useMemo } from 'react';
import { ScaleOrdinal, scaleRectangleData } from 'eazychart-core/src';
import { Bar } from '@/components/shapes/Bar';
import { useChart } from '@/lib/use-chart';
import { useCartesianScales } from '@/components/scales/CartesianScale';
import { useColorScale } from './scales/ColorScale';
import {
  RectangleDatum,
  ScaleLinearOrBand,
  Dimensions,
} from 'eazychart-core/src/types';

export interface BarsProps extends SVGAttributes<SVGGElement> {
  xDomainKey: string;
  yDomainKey: string;
  scopedSlots?: {
    default: ({
      shapeData,
      scales,
      dimensions,
    }: {
      shapeData: RectangleDatum[];
      scales: {
        xScale: ScaleLinearOrBand;
        yScale: ScaleLinearOrBand;
        colorScale: ScaleOrdinal;
      };
      dimensions: Dimensions;
    }) => JSX.Element[];
  };
}

export const Bars: FC<BarsProps> = ({
  xDomainKey,
  yDomainKey,
  scopedSlots,
  ...rest
}) => {
  const { data, dimensions, isRTL } = useChart();
  const { xScale, yScale } = useCartesianScales();
  const { colorScale } = useColorScale();

  const scaledData = useMemo(() => {
    return scaleRectangleData(
      data,
      xDomainKey,
      yDomainKey,
      xScale,
      yScale,
      colorScale,
      dimensions,
      isRTL
    );
  }, [
    data,
    xDomainKey,
    yDomainKey,
    xScale,
    yScale,
    colorScale,
    dimensions,
    isRTL,
  ]);

  return (
    <g className="ez-bars" {...rest}>
      {scopedSlots && scopedSlots.default
        ? scopedSlots.default({
            shapeData: scaledData,
            scales: { xScale, yScale, colorScale },
            dimensions,
          })
        : scaledData.map((rectDatum) => {
            return <Bar key={rectDatum.id} shapeDatum={rectDatum} />;
          })}
    </g>
  );
};

// packages/ez-vue/src/components/Bars.tsx
import Vue from 'vue';
import Component from 'vue-class-component';
import { ChartContext, ScaleLinearOrBand } from 'eazychart-core/src/types';
import { InjectReactive, Prop } from 'vue-property-decorator';
import { ScaleOrdinal, scaleRectangleData } from 'eazychart-core/src';
import Bar from '@/components/shapes/Bar';

@Component({ components: { Bar } })
export default class Bars extends Vue {
  @InjectReactive('chart')
  private chart!: ChartContext;

  @InjectReactive('cartesianScale')
  private cartesianScale!: { xScale: ScaleLinearOrBand, yScale: ScaleLinearOrBand };

  @InjectReactive('colorScale')
  private colorScale!: ScaleOrdinal;

  @Prop({
    type: String,
    required: true,
  })
  private readonly xDomainKey!: string;

  @Prop({
    type: String,
    required: true,
  })
  private readonly yDomainKey!: string;

  get shapeData() {
    return scaleRectangleData(
      this.chart.data,
      this.xDomainKey,
      this.yDomainKey,
      this.cartesianScale.xScale,
      this.cartesianScale.yScale,
      this.colorScale,
      this.chart.dimensions,
      this.chart.isRTL,
    );
  }

  render() {
    const {
      shapeData, chart, $scopedSlots, cartesianScale, colorScale,
    } = this;
    const { dimensions } = chart;

    return (
      <g class="ez-bars">
        {$scopedSlots.default
          ? $scopedSlots.default({
            shapeData,
            scales: { ...cartesianScale, colorScale },
            dimensions,
          })
          : shapeData.map((rectDatum) => (
              <Bar shapeDatum={rectDatum} key={rectDatum.id} />
          ))}
      </g>
    );
  }
}
