// packages/ez-react/src/components/BubbleMap.tsx
import React, { SVGAttributes, useMemo } from 'react';
import {
  calculateGeoProjectionCenter,
  scaleGeoFeatureData,
} from 'eazychart-core/src';
import { GeoFeatureCollection, MapConfig } from 'eazychart-core/src/types';
import { BubbleConfig } from 'eazychart-core/src/utils/types';

import { BubbleMapPath } from './shapes/BubbleMapPath';
import { useColorScale } from './scales/ColorScale';
import { useChart } from '@/lib/use-chart';

export interface BubbleMapChartProps extends SVGAttributes<SVGPathElement> {
  isWrapped?: boolean;
  map: MapConfig;
  bubbles: BubbleConfig;
  geoJson: GeoFeatureCollection;
}

export const BubbleMap: React.FC<BubbleMapChartProps> = ({
  geoJson,
  bubbles,
  map,

  ...rest
}: BubbleMapChartProps) => {
  const { projectionType, geoDomainKey, valueDomainKey, fill, stroke } = map;
  const { colorScale } = useColorScale();
  const { data, dimensions } = useChart();

  const projectionCenter = useMemo(
    () => calculateGeoProjectionCenter(geoJson, projectionType, dimensions),
    [geoJson, projectionType, dimensions]
  );

  const shapeData = useMemo(() => {
    return scaleGeoFeatureData(
      data,
      geoJson?.features || [],
      geoDomainKey,
      valueDomainKey,
      colorScale,
      fill
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data, geoJson?.features, geoDomainKey, colorScale.scale]);

  return (
    <g {...rest} className="ez-map">
      {shapeData.map((shapeDatum, idx) => {
        return (
          <BubbleMapPath
            key={idx}
            shapeDatum={shapeDatum}
            projectionType={projectionType}
            projectionCenter={projectionCenter}
            stroke={stroke}
            fill={fill}
            bubbles={bubbles}
          />
        );
      })}
    </g>
  );
};

// packages/ez-vue/src/components/BubbleMap.tsx
import Vue, { PropType } from 'vue';
import Component from 'vue-class-component';
import {
  MapConfig,
  GeoFeatureCollection,
  ChartContext,
  AnyScale,
  BubbleConfig,
} from 'eazychart-core/src/types';
import { InjectReactive, Prop } from 'vue-property-decorator';
import {
  calculateGeoProjectionCenter,
  scaleGeoFeatureData,
} from 'eazychart-core/src';
import BubbleMapPath from './shapes/BubbleMapPath';

@Component({ components: { BubbleMapPath } })
export default class BubbleMap extends Vue {
  @Prop({
    type: Object as PropType<MapConfig>,
  })
  private readonly map!: MapConfig;

  @Prop({
    type: Object as PropType<GeoFeatureCollection>,
  })
  private readonly geoJson!: GeoFeatureCollection;

  @Prop({
    type: Object as PropType<BubbleConfig>,
  })
  private readonly bubbles!: BubbleConfig;

  @InjectReactive('colorScale')
  private colorScale!: AnyScale;

  @InjectReactive('chart')
  private chart!: ChartContext;

  get projectionCenter() {
    const { geoJson, chart, map } = this;
    const { dimensions } = chart;
    const { projectionType } = map;
    return calculateGeoProjectionCenter(geoJson, projectionType, dimensions);
  }

  get shapeData() {
    const {
      geoJson, chart, colorScale, map,
    } = this;
    const { data } = chart;
    const { geoDomainKey, valueDomainKey, fill } = map;
    return scaleGeoFeatureData(
      data,
      geoJson?.features || [],
      geoDomainKey,
      valueDomainKey,
      colorScale,
      fill,
    );
  }

  render() {
    const {
      map, projectionCenter, shapeData, bubbles,
    } = this;

    return (
      <g class="ez-map">
        {shapeData.map((shapeDatum, idx) => (
            <BubbleMapPath
              key={idx}
              shapeDatum={shapeDatum}
              projectionType={map.projectionType}
              projectionCenter={projectionCenter}
              stroke={map.stroke}
              fill={map.fill}
              bubbles={bubbles}
              />
        ))}
      </g>
    );
  }
}
