// packages/ez-react/src/components/MapBubbles.tsx
import React, { FC, useMemo } from 'react';
import { scaleMapBubbleData } from 'eazychart-core/src';
import { PointDatum } from 'eazychart-core/src/types';
import { useChart } from '@/lib/use-chart';
import { Bubble } from '@/components/shapes/Bubble';
import { useSqrtScale } from './scales/SqrtScale';
import { useMap } from '@/lib/use-map';
import { useColorScale } from './scales/ColorScale';

export interface MapBubblesProps {
  geoDomainKey: string;
  rDomainKey: string;
  stroke?: string;
  strokeWidth?: number;
  opacity?: number;
  scopedSlots?: {
    default: ({ shapeData }: { shapeData: PointDatum[] }) => React.ReactChild;
  };
}

export const MapBubbles: FC<MapBubblesProps> = ({
  geoDomainKey,
  rDomainKey,
  stroke,
  strokeWidth,
  opacity,
  scopedSlots,
  ...rest
}) => {
  const { data } = useChart();
  const { sqrtScale: rScale } = useSqrtScale();
  const { projection, mapData } = useMap();
  const { colorScale } = useColorScale();

  const shapeData = useMemo(() => {
    return scaleMapBubbleData(
      data,
      mapData,
      geoDomainKey,
      rDomainKey,
      projection,
      rScale,
      colorScale
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data, projection, geoDomainKey, rDomainKey, rScale]);

  if (scopedSlots && scopedSlots.default) {
    return (
      <g className="ez-map-bubbles" {...rest}>
        {scopedSlots.default({ shapeData })}
      </g>
    );
  }

  return (
    <g className="ez-map-bubbles" {...rest}>
      {shapeData.map((shapeDatum) => {
        return (
          <Bubble
            shapeDatum={shapeDatum}
            key={shapeDatum.id}
            stroke={stroke}
            strokeWidth={strokeWidth}
            opacity={opacity}
          />
        );
      })}
    </g>
  );
};

// packages/ez-vue/src/components/MapBubbles.tsx
import Vue from 'vue';
import Component from 'vue-class-component';
import { AnyScale, ChartContext, MapContext } from 'eazychart-core/src/types';
import { InjectReactive, Prop } from 'vue-property-decorator';
import { ScaleSqrt, scaleMapBubbleData } from 'eazychart-core/src';
import Bubble from './shapes/Bubble';

@Component({ components: { Bubble } })
export default class Bubbles extends Vue {
  @InjectReactive('chart')
  private chart!: ChartContext;

  @InjectReactive('mapContext')
  private mapContext!: MapContext;

  @InjectReactive('colorScale')
  private colorScale!: AnyScale;

  @InjectReactive('sqrtScale')
  private rScale!: ScaleSqrt;

  @Prop({
    type: Number,
    required: true,
  })
  private readonly strokeWidth!: number;

  @Prop({
    type: Number,
    required: true,
  })
  private readonly opacity!: number;

  @Prop({
    type: String,
    required: true,
  })
  private readonly stroke!: string;

  @Prop({
    type: String,
    required: true,
  })
  private readonly geoDomainKey!: string;

  @Prop({
    type: String,
    required: true,
  })
  private readonly rDomainKey!: string;

  get shapeData() {
    const { chart, mapContext, colorScale } = this;
    const { mapData, projection } = mapContext;
    return scaleMapBubbleData(
      chart.data,
      mapData,
      this.geoDomainKey,
      this.rDomainKey,
      projection,
      this.rScale,
      colorScale,
    );
  }

  render() {
    const {
      shapeData, $scopedSlots, stroke, strokeWidth, opacity,
    } = this;

    if ($scopedSlots.default) {
      return (
        <g class="ez-map-bubbles">{$scopedSlots.default({ shapeData })}</g>
      );
    }

    return (
      <g class="ez-map-bubbles">
        {shapeData.map((shapeDatum) => (
          <Bubble
            shapeDatum={shapeDatum}
            key={shapeDatum.id}
            stroke={stroke}
            strokeWidth={strokeWidth}
            opacity={opacity}
          />
        ))}
      </g>
    );
  }
}
