// packages/ez-react/src/components/StackedBars.tsx
import React, { FC, SVGAttributes, useMemo } from 'react';
import { scaleRectangleData } from 'eazychart-core/src';
import { Bar } from '@/components/shapes/Bar';
import { useChart } from '@/lib/use-chart';
import { useCartesianScales } from '@/components/scales/CartesianScale';
import { useColorScale } from './scales/ColorScale';
import { Direction, RectangleDatum } from 'eazychart-core/src/types';

export interface StackedBarsProps extends SVGAttributes<SVGGElement> {
  domainKey: string;
  stackDomainKeys: string[];
  direction: Direction.HORIZONTAL | Direction.VERTICAL;
}

export const StackedBars: FC<StackedBarsProps> = ({
  domainKey,
  stackDomainKeys,
  direction = Direction.VERTICAL,
  ...rest
}) => {
  const { data, dimensions, isRTL } = useChart();
  const { xScale, yScale } = useCartesianScales();
  const { colorScale } = useColorScale();

  const scaledDataDict = useMemo(() => {
    return stackDomainKeys.reduce(
      (acc: { [key: string]: RectangleDatum[] }, yDomainKey) => {
        acc[yDomainKey] = scaleRectangleData(
          data,
          domainKey,
          yDomainKey,
          xScale,
          yScale,
          colorScale,
          dimensions,
          isRTL
        );
        return acc;
      },
      {}
    );
  }, [
    data,
    stackDomainKeys,
    domainKey,
    xScale,
    yScale,
    colorScale,
    dimensions,
    isRTL,
  ]);

  return (
    <g className="ez-stacked-bars" {...rest}>
      {data.map((_datum, idx) => {
        return (
          // The Domain keys still needs to be sorted.
          // We create a bar for every data row
          // Each bar is a stack bar where every element is a domain key.
          <g className="ez-stacked-bar">
            {stackDomainKeys.map((yDomainKey, domainIdx) => {
              const color = colorScale.scale(yDomainKey);
              const scaledData = scaledDataDict[yDomainKey][idx];
              // The first domain key will not be affected.
              const previousRectWidth =
                domainIdx !== 0
                  ? scaledDataDict[stackDomainKeys[domainIdx - 1]][idx].width
                  : 0;
              const previousRectHeight =
                domainIdx !== 0
                  ? scaledDataDict[stackDomainKeys[domainIdx - 1]][idx].height
                  : 0;
              const shapeDatum =
                // The height or the width of the current bar will be computed depending to the orientaion
                // the height will be currentDKHeight - previousDKHeight (same for the width)
                {
                  ...scaledData,
                  width:
                    direction === Direction.HORIZONTAL
                      ? scaledData.width - previousRectWidth
                      : scaledData.width,
                  height:
                    direction === Direction.VERTICAL
                      ? scaledData.height - previousRectHeight
                      : scaledData.height,
                };

              return (
                <Bar
                  key={`${yDomainKey}${idx}`}
                  shapeDatum={{ ...shapeDatum, color }}
                />
              );
            })}
          </g>
        );
      })}
    </g>
  );
};

// packages/ez-vue/src/components/StackedBars.tsx
import Vue, { PropType } from 'vue';
import Component from 'vue-class-component';
import {
  ChartContext,
  Direction,
  RectangleDatum,
  ScaleLinearOrBand,
} from 'eazychart-core/src/types';
import { InjectReactive, Prop } from 'vue-property-decorator';
import { ScaleOrdinal, scaleRectangleData } from 'eazychart-core/src';
import Bar from '@/components/shapes/Bar';

@Component({ components: { Bar } })
export default class StackedBars extends Vue {
  @InjectReactive('chart')
  private chart!: ChartContext;

  @InjectReactive('cartesianScale')
  private cartesianScale!: {
    xScale: ScaleLinearOrBand;
    yScale: ScaleLinearOrBand;
  };

  @Prop({
    type: String,
    required: true,
  })
  private readonly singleDomainKey!: string;

  @Prop({
    type: Array,
    required: true,
  })
  private readonly stackDomainKeys!: string[];

  @Prop({
    type: String as PropType<Direction>,
    required: true,
  })
  private readonly direction: Direction = Direction.VERTICAL;

  get colorScale() {
    return this.chart.getScale('colorScale') as ScaleOrdinal;
  }

  get scaledDataDict() {
    return this.stackDomainKeys.reduce(
      (acc: { [key: string]: RectangleDatum[] }, yDomainKey) => {
        acc[yDomainKey] = scaleRectangleData(
          this.chart.data,
          this.singleDomainKey,
          yDomainKey,
          this.cartesianScale.xScale,
          this.cartesianScale.yScale,
          this.colorScale,
          this.chart.dimensions,
          this.chart.isRTL,
        );
        return acc;
      },
      {},
    );
  }

  render() {
    const {
      scaledDataDict, chart, stackDomainKeys, colorScale, direction,
    } = this;

    return (
      <g class="ez-stacked-bars">
        {chart.data.map((_datum, idx) => (
          // The Domain keys still needs to be sorted.
          // We create a bar for every data row
          // Each bar is a stack bar where every element is a domain key.
          <g class="ez-stacked-bar">
            {stackDomainKeys.map((yDomainKey, domainIdx) => {
              const color = colorScale.scale(yDomainKey);
              const scaledData = scaledDataDict[yDomainKey][idx];
              // The first domain key will not be affected.
              const previousRectWidth = domainIdx !== 0
                ? scaledDataDict[stackDomainKeys[domainIdx - 1]][idx].width
                : 0;
              const previousRectHeight = domainIdx !== 0
                ? scaledDataDict[stackDomainKeys[domainIdx - 1]][idx].height
                : 0;
              // The height or the width of the current bar will be computed depending
              // to the orientaion
              // the height will be currentDKHeight - previousDKHeight (same for the width)
              const shapeDatum = {
                ...scaledData,
                width:
                  direction === Direction.HORIZONTAL
                    ? scaledData.width - previousRectWidth
                    : scaledData.width,
                height:
                  direction === Direction.VERTICAL
                    ? scaledData.height - previousRectHeight
                    : scaledData.height,
              };

              return (
                <Bar
                  key={`${yDomainKey}${idx}`}
                  shapeDatum={{ ...shapeDatum, color }}
                />
              );
            })}
          </g>
        ))}
      </g>
    );
  }
}
