// packages/ez-vue/src/components/scales/grid/Grid.tsx
import Vue, { PropType } from 'vue';
import Component from 'vue-class-component';
import { Prop } from 'vue-property-decorator';
import { Direction } from 'eazychart-core/src/types';
import { ScaleBand, ScaleLinear } from 'eazychart-core/src';
import GridLines from './GridLines';

@Component
export default class Grid extends Vue {
  @Prop({
    type: Array,
    default() {
      return [Direction.HORIZONTAL, Direction.VERTICAL];
    },
  })
  private readonly directions!: Direction[];

  @Prop({
    type: Object as PropType<ScaleBand | ScaleLinear>,
    required: true,
  })
  private readonly xScale!: ScaleBand | ScaleLinear;

  @Prop({
    type: Object as PropType<ScaleBand | ScaleLinear>,
    required: true,
  })
  private readonly yScale!: ScaleBand | ScaleLinear;

  @Prop({
    type: String,
    default: '#a8a8a8',
  })
  private readonly color!: string;

  render() {
    const {
      directions, color, xScale, yScale,
    } = this;

    if (!directions || directions.length === 0) {
      return null;
    }

    return (
      <g class="ez-grid">
        {directions.includes(Direction.HORIZONTAL) && (
          <GridLines
            direction={Direction.HORIZONTAL}
            aScale={yScale}
            color={color}
          />
        )}
        {directions.includes(Direction.VERTICAL) && (
          <GridLines
            direction={Direction.VERTICAL}
            aScale={xScale}
            color={color}
          />
        )}
      </g>
    );
  }
}

// packages/ez-react/src/components/scales/grid/Grid.tsx
import React, { FC, SVGAttributes } from 'react';
import { Direction, GridConfig } from 'eazychart-core/src/types';
import { GridLines } from './GridLines';
import { ScaleBand, ScaleLinear } from 'eazychart-core/src';

export interface GridProps
  extends Omit<SVGAttributes<SVGRectElement>, 'directions'>,
    GridConfig {
  xScale: ScaleBand | ScaleLinear;
  yScale: ScaleBand | ScaleLinear;
}

export const Grid: FC<GridProps> = ({
  directions = [Direction.HORIZONTAL, Direction.VERTICAL],
  color = '#a8a8a8',
  xScale,
  yScale,
  ...rest
}) => {
  return Array.isArray(directions) && directions.length > 0 ? (
    <g className="ez-grid" {...rest}>
      {directions.includes(Direction.HORIZONTAL) && (
        <GridLines
          color={color}
          direction={Direction.HORIZONTAL}
          aScale={yScale}
        />
      )}
      {directions.includes(Direction.VERTICAL) && (
        <GridLines
          color={color}
          direction={Direction.VERTICAL}
          aScale={xScale}
        />
      )}
    </g>
  ) : null;
};
