// packages/ez-vue/src/components/addons/tooltip/TooltipProvider.tsx
import Vue from 'vue';
import Component from 'vue-class-component';
import { InjectReactive, Provide, Watch } from 'vue-property-decorator';
import {
  TooltipContext,
  ChartContext,
  Point,
  ShapeDatum,
  NormalizedDatum,
} from 'eazychart-core/src/types';
import { debounce } from 'eazychart-core/src';
import Fragment from '@/lib/Fragment';
import Tooltip from './Tooltip';

@Component
export default class TooltipProvider extends Vue {
  @InjectReactive('chart')
  private chart!: ChartContext;

  @Provide('tooltip')
  // @ts-ignore
  private tooltip: TooltipContext = {
    showTooltip: this.showTooltip,
    moveTooltip: debounce(this.moveTooltip, 50).bind(this),
    hideTooltip: this.hideTooltip,
  };

  private datum: NormalizedDatum | null = null;

  private shapeDatum: ShapeDatum | null = null;

  private isVisible = false;

  private mousePosition: Point = { x: 0, y: 0 };

  @Watch('chart.dimensions')
  onDimensionsChange() {
    this.mousePosition = {
      x: this.chart.dimensions.width / 2,
      y: this.chart.dimensions.height / 2,
    };
  }

  get domains() {
    return this.chart.scales
      .filter(({ definition }) => typeof definition.domainKey === 'string')
      .map(({ definition }) => definition.domainKey);
  }

  showTooltip(shapeDatum: ShapeDatum) {
    const d = shapeDatum.id in this.chart.dataDict
      ? this.chart.dataDict[shapeDatum.id]
      : null;
    this.datum = d;
    this.shapeDatum = shapeDatum;
    this.isVisible = true;
  }

  moveTooltip(_shapeDatum: ShapeDatum, event: MouseEvent) {
    this.mousePosition = { x: event.clientX, y: event.clientY };
  }

  hideTooltip(_shapeDatum: ShapeDatum, _event: MouseEvent) {
    this.isVisible = false;
  }

  render() {
    const tooltipProps = {
      datum: this.datum,
      shapeDatum: this.shapeDatum,
      isVisible: this.isVisible,
      mousePosition: this.mousePosition,
      domains: this.domains,
    };
    const DefaultSlot = this.$scopedSlots.default
      ? this.$scopedSlots.default({})
      : null;
    const TooltipOverride = this.$scopedSlots.Tooltip
      ? this.$scopedSlots.Tooltip(tooltipProps)
      : null;
    return (
      <Fragment type="div" name="tooltip">
        {DefaultSlot}
        {TooltipOverride || <Tooltip props={tooltipProps} />}
      </Fragment>
    );
  }
}

// packages/ez-react/src/components/addons/tooltip/TooltipProvider.tsx
import React, { FC, useCallback, useEffect, useMemo, useState } from 'react';
import { NormalizedDatum, Point, ShapeDatum } from 'eazychart-core/src/types';
import { debounce, AbstractScale } from 'eazychart-core/src';
import { Fragment } from '@/lib/Fragment';
import { useChart } from '@/lib/use-chart';
import { TooltipProps } from './Tooltip';
import { TooltipContext } from './TooltipContext';

export interface TooltipProviderProps {
  Tooltip?: FC<TooltipProps>;
  isWrapped?: boolean;
}

export const TooltipProvider: FC<TooltipProviderProps> = ({
  Tooltip,
  children,
  isWrapped = true,
}) => {
  const { dataDict, scales, dimensions } = useChart();
  const [isVisible, setIsVisible] = useState(false);
  const [datum, setDatum] = useState<NormalizedDatum | null>(null);
  const [shapeDatum, setShapeDatum] = useState<ShapeDatum | null>(null);
  const [mousePosition, setMousePosition] = useState<Point>({ x: 0, y: 0 });
  useEffect(() => {
    setMousePosition({ x: dimensions.width / 2, y: dimensions.height / 2 });
  }, [dimensions]);

  const domains = useMemo(() => {
    if (scales !== undefined) {
      return (scales as AbstractScale[])
        .filter(({ definition }) => typeof definition.domainKey === 'string')
        .map(({ definition }) => definition.domainKey) as string[];
    }
    return [];
  }, [scales]);

  const showTooltip = useCallback(
    (shapeDatum: ShapeDatum, _event: MouseEvent) => {
      const d = shapeDatum.id in dataDict ? dataDict[shapeDatum.id] : null;
      setDatum(d);
      setShapeDatum(shapeDatum);
      setIsVisible(true);
    },
    [dataDict, setDatum, setShapeDatum, setIsVisible]
  );

  const moveTooltip = useMemo(
    () =>
      debounce((_shapeDatum: ShapeDatum, event: MouseEvent) => {
        setMousePosition({ x: event.clientX, y: event.clientY });
      }, 50),
    [setMousePosition]
  );

  const hideTooltip = useCallback(
    (_shapeDatum: ShapeDatum, _event: MouseEvent) => {
      setIsVisible(false);
    },
    [setIsVisible]
  );

  const tooltipProps = {
    datum,
    shapeDatum,
    isVisible,
    mousePosition,
    domains,
  };

  const TooltipOverride = Tooltip ? <Tooltip {...tooltipProps} /> : null;
  return (
    <TooltipContext.Provider
      value={{
        showTooltip,
        moveTooltip,
        hideTooltip,
      }}
    >
      {isWrapped ? (
        <Fragment type="div" name="tooltip">
          {children}
          {TooltipOverride}
        </Fragment>
      ) : (
        <>
          {children}
          {TooltipOverride}
        </>
      )}
    </TooltipContext.Provider>
  );
};
